### ISSUE TITLE
kube-dns in CrashLoopBackOff (kubernetes 1.9)

### ISSUE THREAD

**Issue by jimcm** [weaveworks/weave#3448] opened 2018-11-08 22:24 UTC
## What you expected to happen?

I ran kubeadm init and expected all pods in the kube-system namespace to start up without error

## What happened?

kube-dns enters CrashLoopBackOff and stays there

```
# kubectl get pods -o wide  --all-namespaces
NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE       IP              NODE
kube-system   etcd-mtpnjvzonap001                      1/1       Running            0          1d        135.21.27.139   mtpnjvzonap001
kube-system   kube-apiserver-mtpnjvzonap001            1/1       Running            0          1d        135.21.27.139   mtpnjvzonap001
kube-system   kube-controller-manager-mtpnjvzonap001   1/1       Running            0          1d        135.21.27.139   mtpnjvzonap001
kube-system   kube-dns-6f4fd4bdf-c4qrz                 1/3       CrashLoopBackOff   18         32m       10.32.0.1       mtpnjvzonap001
kube-system   kube-proxy-9p4h9                         1/1       Running            0          1d        135.21.27.139   mtpnjvzonap001
kube-system   kube-scheduler-mtpnjvzonap001            1/1       Running            0          1d        135.21.27.139   mtpnjvzonap001
kube-system   weave-net-qfbnd                          2/2       Running            0          21h       135.21.27.139   mtpnjvzonap001
```

```
#kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   1d
```

The log of kube-dns shows this, I assume the i/o timeout indicates something wrong with pod network leaving kube-dns unable to reach apiserver

```
I1107 18:28:52.711651       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E1107 18:28:52.711942       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
```
From the host, I am able to connect to apiserver 

```
#telnet -e % 10.96.0.1 443
Telnet escape character is '%'.
Trying 10.96.0.1...
Connected to 10.96.0.1.
```
My telnet connection is confirmed in the apiserver log

```
#kubectl logs -n kube-system kube-apiserver-mtpnjvzonap001
I1108 22:06:12.293047       1 logs.go:41] http: TLS handshake error from 135.21.27.139:46922: EOF

```

## How to reproduce it?

I started kubernetes by running

```
#kubeadm init --ignore-preflight-errors=cri  --pod-network-cidr=10.32.0.0/12
#kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#kubectl taint nodes --all node-role.kubernetes.io/master-
```

## Anything else we need to know?

Running Kubernetes on Ubuntu VM on KVM Host

Relevant linux kernel parameters

```
#sysctl net.bridge.bridge-nf-call-iptables
net.bridge.bridge-nf-call-iptables = 1
#sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

## Versions:

```
#weave version
weave script 2.5.0
weave 2.5.0
#docker version
Client:
 Version:      1.13.1-cs8
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   91ca5f2
 Built:        Fri Nov 17 01:02:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-cs8
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   91ca5f2
 Built:        Fri Nov 17 01:02:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
#uname -a
Linux mtpnjvzonap001 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
#kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:47:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
#

```

## Logs:

```
#kubectl logs -n kube-system weave-net-qfbnd weave
INFO: 2018/11/07 23:22:55.251394 Command line options: map[conn-limit:100 expect-npc:true ipalloc-range:10.32.0.0/12 name:aa:53:be:75:71:f7 no-dns:true datapath:datapath http-addr:127.0.0.1:6784 ipalloc-init:consensus=1 metrics-addr:0.0.0.0:6782 db-prefix:/weavedb/weave-net docker-api: host-root:/host nickname:mtpnjvzonap001 port:6783]
INFO: 2018/11/07 23:22:55.251495 weave  2.5.0
INFO: 2018/11/07 23:22:55.370933 Bridge type is bridged_fastdp
INFO: 2018/11/07 23:22:55.370970 Communication between peers is unencrypted.
INFO: 2018/11/07 23:22:55.373182 Our name is aa:53:be:75:71:f7(mtpnjvzonap001)
INFO: 2018/11/07 23:22:55.373219 Launch detected - using supplied peer list: [135.21.27.139]
INFO: 2018/11/07 23:22:55.383964 Checking for pre-existing addresses on weave bridge
INFO: 2018/11/07 23:22:55.402607 [allocator aa:53:be:75:71:f7] No valid persisted data
INFO: 2018/11/07 23:22:55.409702 [allocator aa:53:be:75:71:f7] Initialising via deferred consensus
INFO: 2018/11/07 23:22:55.409762 Sniffing traffic on datapath (via ODP)
INFO: 2018/11/07 23:22:55.410119 ->[135.21.27.139:6783] attempting connection
INFO: 2018/11/07 23:22:55.410361 ->[135.21.27.139:51299] connection accepted
INFO: 2018/11/07 23:22:55.410963 ->[135.21.27.139:51299|aa:53:be:75:71:f7(mtpnjvzonap001)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/11/07 23:22:55.411011 ->[135.21.27.139:6783|aa:53:be:75:71:f7(mtpnjvzonap001)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/11/07 23:22:55.413602 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2018/11/07 23:22:55.414144 Listening for metrics requests on 0.0.0.0:6782
INFO: 2018/11/07 23:22:56.173515 [kube-peers] Added myself to peer list &{[{aa:53:be:75:71:f7 mtpnjvzonap001}]}
DEBU: 2018/11/07 23:22:56.177794 [kube-peers] Nodes that have disappeared: map[]
10.32.0.2
DEBU: 2018/11/07 23:22:56.293034 registering for updates for node delete events
135.21.27.139
INFO: 2018/11/07 23:23:25.448268 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=3f319f37-e29d-11e8-88df-525400314503&flag_kubernetes-version=v1.9.11&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 172.217.0.147:443: i/o timeout
INFO: 2018/11/08 06:13:01.118355 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=3f319f37-e29d-11e8-88df-525400314503&flag_kubernetes-version=v1.9.11&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 172.217.0.147:443: i/o timeout
INFO: 2018/11/08 12:10:25.845363 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=3f319f37-e29d-11e8-88df-525400314503&flag_kubernetes-version=v1.9.11&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 216.58.218.115:443: i/o timeout
INFO: 2018/11/08 17:11:34.020630 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=3f319f37-e29d-11e8-88df-525400314503&flag_kubernetes-version=v1.9.11&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 172.217.164.83:443: i/o timeout
#

```

## Network:

```
```
#ip route
default via 135.21.27.129 dev eth0 onlink
10.32.0.0/12 dev weave  proto kernel  scope link  src 10.32.0.2
135.21.27.128/26 dev eth0  proto kernel  scope link  src 135.21.27.139
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
#ip -4 -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 135.21.27.139/26 brd 135.21.27.191 scope global eth0\       valid_lft forever preferred_lft forever
3: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever
21: weave    inet 10.32.0.2/12 brd 10.47.255.255 scope global weave\       valid_lft forever preferred_lft forever
#iptables-save
#Generated by iptables-save v1.6.0 on Thu Nov  8 21:53:00 2018
*nat
:PREROUTING ACCEPT [20:800]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [2:152]
:POSTROUTING ACCEPT [2:152]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-XQPNEUO6WT44Y3EH - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:WEAVE - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -j WEAVE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-XQPNEUO6WT44Y3EH -s 135.21.27.139/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-XQPNEUO6WT44Y3EH -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 135.21.27.139:6443
-A KUBE-SERVICES ! -s 10.32.0.0/12 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.32.0.0/12 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.32.0.0/12 -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-XQPNEUO6WT44Y3EH
-A WEAVE -s 10.32.0.0/12 -d 224.0.0.0/4 -j RETURN
-A WEAVE ! -s 10.32.0.0/12 -d 10.32.0.0/12 -j MASQUERADE
-A WEAVE -s 10.32.0.0/12 ! -d 10.32.0.0/12 -j MASQUERADE
COMMIT
#Completed on Thu Nov  8 21:53:00 2018
#Generated by iptables-save v1.6.0 on Thu Nov  8 21:53:00 2018
*filter
:INPUT ACCEPT [2040:502107]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2032:511923]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-SERVICES - [0:0]
:WEAVE-NPC - [0:0]
:WEAVE-NPC-DEFAULT - [0:0]
:WEAVE-NPC-EGRESS - [0:0]
:WEAVE-NPC-EGRESS-ACCEPT - [0:0]
:WEAVE-NPC-EGRESS-CUSTOM - [0:0]
:WEAVE-NPC-EGRESS-DEFAULT - [0:0]
:WEAVE-NPC-INGRESS - [0:0]
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -j KUBE-FIREWALL
-A INPUT -i weave -j WEAVE-NPC-EGRESS
-A FORWARD -i weave -m comment --comment "NOTE: this must go before \'-j KUBE-FORWARD\'" -j WEAVE-NPC-EGRESS
-A FORWARD -o weave -m comment --comment "NOTE: this must go before \'-j KUBE-FORWARD\'" -j WEAVE-NPC
-A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
-A FORWARD -o weave -j DROP
-A FORWARD -i weave ! -o weave -j ACCEPT
-A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 10.32.0.0/12 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.32.0.0/12 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
-A WEAVE-NPC -m physdev --physdev-out vethwe-bridge -j ACCEPT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
-A WEAVE-NPC-DEFAULT -m set --match-set weave-;rGqyMIl1HN^cfDki\~Z$3]6!N dst -m comment --comment "DefaultAllow ingress isolation for namespace: default" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-P.B|!ZhkAr5q=XZ?3}tMBA+0 dst -m comment --comment "DefaultAllow ingress isolation for namespace: kube-system" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-Rzff}h:=]JaaJl/G;(XJpGjZ[ dst -m comment --comment "DefaultAllow ingress isolation for namespace: kube-public" -j ACCEPT
-A WEAVE-NPC-EGRESS -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC-EGRESS -m physdev --physdev-in vethwe-bridge -j RETURN
-A WEAVE-NPC-EGRESS -d 224.0.0.0/4 -j RETURN
-A WEAVE-NPC-EGRESS -m state --state NEW -j WEAVE-NPC-EGRESS-DEFAULT
-A WEAVE-NPC-EGRESS -m state --state NEW -m mark ! --mark 0x40000/0x40000 -j WEAVE-NPC-EGRESS-CUSTOM
-A WEAVE-NPC-EGRESS -m state --state NEW -m mark ! --mark 0x40000/0x40000 -j NFLOG --nflog-group 86
-A WEAVE-NPC-EGRESS -m mark ! --mark 0x40000/0x40000 -j DROP
-A WEAVE-NPC-EGRESS-ACCEPT -j MARK --set-xmark 0x40000/0x40000
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-s_+ChJId4Uy_$}G;WdH|\~TK)I src -m comment --comment "DefaultAllow egress isolation for namespace: default" -j WEAVE-NPC-EGRESS-ACCEPT
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-s_+ChJId4Uy_$}G;WdH|\~TK)I src -m comment --comment "DefaultAllow egress isolation for namespace: default" -j RETURN
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-E1ney4o[ojNrLk.6rOHi;7MPE src -m comment --comment "DefaultAllow egress isolation for namespace: kube-system" -j WEAVE-NPC-EGRESS-ACCEPT
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-E1ney4o[ojNrLk.6rOHi;7MPE src -m comment --comment "DefaultAllow egress isolation for namespace: kube-system" -j RETURN
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-41s)5vQ^o/xWGz6a20N:\~?#|E src -m comment --comment "DefaultAllow egress isolation for namespace: kube-public" -j WEAVE-NPC-EGRESS-ACCEPT
-A WEAVE-NPC-EGRESS-DEFAULT -m set --match-set weave-41s)5vQ^o/xWGz6a20N:\~?#|E src -m comment --comment "DefaultAllow egress isolation for namespace: kube-public" -j RETURN
COMMIT
```

```

**Comment by murali-reddy** [comment] 2018-11-09 08:53
> The log of kube-dns shows this, I assume the i/o timeout indicates something wrong with pod network leaving kube-dns unable to reach apiserver

Please note the error in kube-dns log `tcp 10.96.0.1:443: i/o timeout`. Its the service IP of kube-dns service being accessed by the kube-dns pod. Plese run through the service [debug steps](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/) to ensure kube-proxy is able to proxy to API endpoint.

**Comment by jimcm** [comment] 2018-11-09 18:13
I ran through debugging steps at https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

Here are steps I ran:

* created the hostnames deployment succesfully
* created the hostnames service successfully
* created a busybox pod for testing

```
NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE
kube-system   busybox                                  1/1       Running            0          47m
kube-system   etcd-mtpnjvzonap001                      1/1       Running            0          2d
kube-system   hostnames-86b6bcdfbc-f4hsq               1/1       Running            0          52m
kube-system   hostnames-86b6bcdfbc-s9pj9               1/1       Running            0          52m
kube-system   hostnames-86b6bcdfbc-tdj9z               1/1       Running            0          52m
kube-system   kube-apiserver-mtpnjvzonap001            1/1       Running            0          2d
kube-system   kube-controller-manager-mtpnjvzonap001   1/1       Running            0          2d
kube-system   kube-dns-6f4fd4bdf-c4qrz                 1/3       CrashLoopBackOff   437        19h
kube-system   kube-proxy-9p4h9                         1/1       Running            0          2d
kube-system   kube-scheduler-mtpnjvzonap001            1/1       Running            0          2d
kube-system   weave-net-qfbnd                          2/2       Running            0          1d

$kubectl get svc -a -n kube-system
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
hostnames   ClusterIP   10.107.61.202   <none>        80/TCP          2h
kube-dns    ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   2d
```

* from the busybox pod, could not lookup the hostnames service in DNS (as expected, as kube-dns is in CrashLoopBackOff)
* from the busybox pod, accessed the hostnames service by the cluster IP successfully
* from the busybox pod, accessed each hostnames pod by its IP successfully
* from the host, accesssed each hostnames pod by its IP successfully
* from the host, cannot access the hostname service by its cluster IP

```
$ echo $http_proxy $https_proxy

$ wget http://10.107.61.202:80
--2018-11-09 17:51:45--  http://10.107.61.202/
Connecting to 10.107.61.202:80... failed: Connection timed out.
```
* kube-proxy is running, log shows no errors

```
$ kubectl logs -n kube-system kube-proxy-9p4h9
I1107 14:54:09.307801       1 feature_gate.go:190] feature gates: map[]
W1107 14:54:09.315508       1 server_others.go:289] Flag proxy-mode="" unknown, assuming iptables proxy
I1107 14:54:09.316901       1 server_others.go:138] Using iptables Proxier.
I1107 14:54:09.325347       1 server_others.go:171] Tearing down inactive rules.
E1107 14:54:09.353410       1 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)
I1107 14:54:09.363497       1 server.go:426] Version: v1.9.11
I1107 14:54:09.384296       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 1048576
I1107 14:54:09.384459       1 conntrack.go:52] Setting nf_conntrack_max to 1048576
I1107 14:54:09.384510       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1107 14:54:09.384557       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1107 14:54:09.384703       1 config.go:102] Starting endpoints config controller
I1107 14:54:09.384742       1 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
I1107 14:54:09.384794       1 config.go:202] Starting service config controller
I1107 14:54:09.384808       1 controller_utils.go:1019] Waiting for caches to sync for service config controller
I1107 14:54:09.484955       1 controller_utils.go:1026] Caches are synced for service config controller
I1107 14:54:09.485018       1 controller_utils.go:1026] Caches are synced for endpoints config controller
```

* kube-proxy is writing IP tables rules

```
$ iptables-save | grep hostnames
-A KUBE-SEP-CL7Q2HWR2FDHYBBW -s 10.32.0.3/32 -m comment --comment "kube-system/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-CL7Q2HWR2FDHYBBW -p tcp -m comment --comment "kube-system/hostnames:" -m tcp -j DNAT --to-destination 10.32.0.3:9376
-A KUBE-SEP-RBOJ5PSJ4KZ5QBX5 -s 10.32.0.5/32 -m comment --comment "kube-system/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-RBOJ5PSJ4KZ5QBX5 -p tcp -m comment --comment "kube-system/hostnames:" -m tcp -j DNAT --to-destination 10.32.0.5:9376
-A KUBE-SEP-VXZOAJCQT6A5OWGF -s 10.32.0.4/32 -m comment --comment "kube-system/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-VXZOAJCQT6A5OWGF -p tcp -m comment --comment "kube-system/hostnames:" -m tcp -j DNAT --to-destination 10.32.0.4:9376
-A KUBE-SERVICES ! -s 10.32.0.0/12 -d 10.107.61.202/32 -p tcp -m comment --comment "kube-system/hostnames: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.107.61.202/32 -p tcp -m comment --comment "kube-system/hostnames: cluster IP" -m tcp --dport 80 -j KUBE-SVC-J7JSTV534HRZRQVN
-A KUBE-SVC-J7JSTV534HRZRQVN -m comment --comment "kube-system/hostnames:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-CL7Q2HWR2FDHYBBW
-A KUBE-SVC-J7JSTV534HRZRQVN -m comment --comment "kube-system/hostnames:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-VXZOAJCQT6A5OWGF
-A KUBE-SVC-J7JSTV534HRZRQVN -m comment --comment "kube-system/hostnames:" -j KUBE-SEP-RBOJ5PSJ4KZ5QBX5
```
* kubelet hairpin mode set to hairpin-veth

```
$ journalctl -u kubelet.service | grep -i hairpin
Nov 07 14:53:34 mtpnjvzonap001 kubelet[127072]: W1107 14:53:34.161677  127072 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to  hairpin-veth"
Nov 07 14:53:34 mtpnjvzonap001 kubelet[127072]: I1107 14:53:34.161703  127072 kubelet.go:580] Hairpin mode set to "hairpin-veth"
```
* Not sure if these hairpin setting are correct?

```
$ for intf in /sys/devices/virtual/net/weave/brif/*; do echo "$intf" ; cat $intf/hairpin_mode; done
/sys/devices/virtual/net/weave/brif/vethwe-bridge
0
/sys/devices/virtual/net/weave/brif/vethwepl0f1fea3
1
/sys/devices/virtual/net/weave/brif/vethwepl16f9d54
1
/sys/devices/virtual/net/weave/brif/vethwepl7284aff
1
/sys/devices/virtual/net/weave/brif/vethweplb7d3924
1
/sys/devices/virtual/net/weave/brif/vethwepld1f1bcb
1
```

**Comment by jimcm** [comment] 2018-11-09 20:46
Not sure if this is related to the problem, but just discovered there are a large number of entries like this in /var/log/kern.log

`Nov  9 20:41:16 mtpnjvzonap001 kernel: [256883.763021] xt_physdev: using --physdev-out in the OUTPUT, FORWARD and POSTROUTING chains for non-bridged traffic is not supported anymore.`

and I do see this in iptables

```
$ iptables-save | fgrep physdev
-A WEAVE-NPC -m physdev --physdev-out vethwe-bridge -j ACCEPT
-A WEAVE-NPC-EGRESS -m physdev --physdev-in vethwe-bridge -j RETURN
```

**Comment by murali-reddy** [comment] 2018-11-12 09:16
@jimcm thanks for running through the debug steps. Regarding the messages you seen in the kernel log. I have opened https://github.com/weaveworks/weave/issues/3449 However this is only warning and used by weave-npc so should not have any functional impact.

Could you please try to kill the `kube-dns` pods so that its get recreated? This might solve the kube-dns CrashLoopBackOff  problem. But going by 
```
from the busybox pod, accessed the hostnames service by the cluster IP successfully
from the busybox pod, accessed each hostnames pod by its IP successfully
from the host, accesssed each hostnames pod by its IP successfully
from the host, cannot access the hostname service by its cluster IP
```
there seems to be problem with kube-proxy. Is this a single node cluster? I am suspecting when you access cluster IP from the host, traffic is getting masqueraded but return traffic is some where getting rejected.

**Comment by jimcm** [comment] 2018-11-12 16:16
yes, this is a single node cluster. 

I killed kube-dns, kubernetes recreated the pod (as expected), but results were same as before, that is, kube-dns pod went into CrashLoopBackOff, and its log showed same error as before:

```
E1112 15:13:09.163680       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1112 15:13:09.163801       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by jimcm** [comment] 2018-11-21 15:35
I still haven't found a resolution for this problem. Are there any other troubleshooting steps I should try?

**Comment by murali-reddy** [comment] 2018-11-22 09:02
Like mentioned earlier problem seems to be with service proxy (kube-proxy). Either pods/host are unable to access the cluster IP for the API service. To narrow down the problem, you may try launching the couple of pods and try pod-to-pod and host-to-pod basic connectivity ping tests. If you see any issue then its some thing caused by Weave. But if you are running to issues only when accessing the service IP, from the pods/hosts then you need to check kube-proxy.

**Comment by thedarkfalcon** [comment] 2019-01-18 02:40
I had a similar problem with weave 2.5.0 that [I described here](https://github.com/kubernetes/kubeadm/issues/578#issuecomment-455352569).

Basically, I couldn't get pods created after installing weave 2.5.0, I rolled back to weave 2.4.1 and my clusters functioned as expected.

**Comment by murali-reddy** [comment] 2019-01-18 04:35
@thedarkfalcon i left a [comment](https://github.com/kubernetes/kubeadm/issues/578#issuecomment-455424447) in the issue. You need to have portmap plugin installed to use weave 2.5. Basically its unrelated to this issue. In this case pods are getting created but are unable to access the API service.

**Comment by fpetkovski** [comment] 2019-06-30 11:21
I had a similar issue as @jimcm, where I could reach kubernetes services from inside the pods.
For me the problem was that I had not specified the `clusterCIDR` in the config for `kube-proxy`. Once I set the value to the same CIDR that weave uses (10.32.0.0/12 by default), services became reachable from inside the pods.

**Comment by bboreham** [comment] 2019-10-11 16:09
Closing - the issue was somewhere in the Kubernetes setup and we never established where.

**Closed by bboreham** 2019-10-11 16:09 UTC
