### ISSUE TITLE
Concerning quantity of netstat entries when using docker weave plugin

### ISSUE THREAD

**Issue by timcharper** [weaveworks/weave#2119] opened 2016-03-31 21:51 UTC
I've rolled out weave with Mesos, Marathon and Docker, and am seeing a concerning amount of netstat entries in netstat

```
unix  3      [ ]         STREAM     CONNECTED     6041473  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6039968
unix  3      [ ]         STREAM     CONNECTED     6041393  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6039961
unix  3      [ ]         STREAM     CONNECTED     6053973
unix  3      [ ]         STREAM     CONNECTED     6028747  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5988988
unix  3      [ ]         STREAM     CONNECTED     6059090  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5985248  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     5985120  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6041275  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6019702  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6014955
unix  3      [ ]         STREAM     CONNECTED     6014919
unix  3      [ ]         STREAM     CONNECTED     6023013  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6038870
unix  3      [ ]         STREAM     CONNECTED     6038183
unix  3      [ ]         STREAM     CONNECTED     6035376
unix  3      [ ]         STREAM     CONNECTED     6040943  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6026729  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6026511  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6026440  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6018652
unix  3      [ ]         STREAM     CONNECTED     5993172
unix  3      [ ]         STREAM     CONNECTED     6025539  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6028308  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     6018225
unix  3      [ ]         STREAM     CONNECTED     5984642  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5981927  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     5981897  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5980732  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     6001441
unix  3      [ ]         STREAM     CONNECTED     5994817
unix  3      [ ]         STREAM     CONNECTED     5996849  /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     5996799  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5989707
unix  3      [ ]         STREAM     CONNECTED     5989536
unix  3      [ ]         STREAM     CONNECTED     5981523  /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     5923266
unix  3      [ ]         STREAM     CONNECTED     5920735
...
```

Counting them in total:

```
netstat -an | grep weave | wc -l
92916
```

I'm only running 9 docker containers at the time, so to see this many connections to weave sockets is understandably concerning.

I've deployed it to five hosts and I'm seeing similar numbers across all of them.

Is this expected?

**Comment by rade** [comment] 2016-03-31 21:57
Docker version?
Weave version?

Is this reproducible outside the context of Marathon?

I've just run some experiments on my machine and am seeing precisely *one* socket, even after starting a bunch of containers with `--net=weave`.

**Comment by timcharper** [comment] 2016-03-31 22:29
I'm checking...

We ran a really large akka cluster load on these machines and it definitely caused a huge influx of network traffic. We've since stopped the job, and it seems that the weave socket connections didn't get cleaned up after the fact.

Weave still works, there's just an ungodly quantity of socket connections. I suspect there's a leak somewhere.

**Comment by timcharper** [comment] 2016-03-31 22:31
CentOS 7.2

```
$ weave version
weave script 1.4.6
weave router 1.4.6
weave proxy  1.4.6
weave plugin 1.4.6

$ docker --version
Docker version 1.10.3, build 20f81dd

```
[tim.harper@sw-analytics47 ~]$ docker ps | grep weaveworks
df0170bde389        weaveworks/plugin:1.4.6                                  "/home/weave/plugin"     3 minutes ago       Up 3 minutes                                                                     weaveplugin
7c1c0b3c7b78        weaveworks/weaveexec:1.4.6                               "/home/weave/weavepro"   3 minutes ago       Up 3 minutes                                                                     weaveproxy
7d610eb02aae        weaveworks/weave:1.4.6                                   "/home/weave/weaver -"   3 minutes ago       Up 3 minutes                                                                     weave
```

**Comment by timcharper** [comment] 2016-03-31 22:35
I've rebooted the machine and am running the same load as before; they've cleared out.

```
$ sudo netstat -pan | grep weave | wc -l
24
```

The rest of the machines still have 90000 of these socket connections open.

**Comment by rade** [comment] 2016-03-31 22:37
Only Docker should be connecting to these sockets, so it would have to be docker that is holding them open.

See whether you can find out what process is using the connections.

**Comment by timcharper** [comment] 2016-03-31 23:05
@rade using `lsof` I've determined that the connections are held by the `plugin` process themselves:

```
# lsos > /mnt/disk8/lsof.out

# cat /mnt/disk8/lsof.out | egrep 'weave.+sock$' | awk '{print $1}' | sort | uniq -c
 654402 plugin
     14 weaveprox

# cat /mnt/disk8/lsof.out | egrep 'weave.+sock$' | head -n 10
plugin     50139                root    5u     unix 0xffff881e2da112c0       0t0    5614010 /run/docker/plugins/weave.sock
plugin     50139                root    6u     unix 0xffff881e2da10f00       0t0    5614012 /run/docker/plugins/weavemesh.sock
plugin     50139                root    8u     unix 0xffff881e3da76180       0t0    5617667 /run/docker/plugins/weavemesh.sock
plugin     50139                root   11u     unix 0xffff881f4f610000       0t0    6401636 /run/docker/plugins/weave.sock
plugin     50139                root   12u     unix 0xffff881e2d8aecc0       0t0    6401638 /run/docker/plugins/weavemesh.sock
plugin     50139                root   13u     unix 0xffff881d47b93fc0       0t0    6401677 /run/docker/plugins/weave.sock
plugin     50139                root   14u     unix 0xffff881e1730bc00       0t0    6392753 /run/docker/plugins/weavemesh.sock
plugin     50139                root   15u     unix 0xffff881dd0627800       0t0    6392764 /run/docker/plugins/weave.sock
plugin     50139                root   16u     unix 0xffff881d4798e540       0t0    6392766 /run/docker/plugins/weavemesh.sock
plugin     50139                root   17u     unix 0xffff881d3e1230c0       0t0    6392777 /run/docker/plugins/weavemesh.sock

# out=$(ps aux); echo "$out" | grep 50139
root      50139  0.4  0.5 1553184 1368864 ?     Ssl  Mar25  44:32 /home/weave/plugin
```

So, it definitely seems that `weaveplugin` is hanging on to them.

**Comment by timcharper** [comment] 2016-03-31 23:07
I've stopped all of the containers except for the weave ones; weave plugin is still hanging on to those connections.

**Comment by rade** [comment] 2016-03-31 23:08
Strange. Can you reproduce this by just running something like `docker run --net=weave --rm alpine /bin/true`?

**Comment by timcharper** [comment] 2016-03-31 23:09
I ran `docker restart weaveplugin` and it cleared them all up. 

```
# docker restart weaveplugin
weaveplugin
# netstat -an | grep weave | wc -l
6
```

**Comment by rade** [comment] 2016-03-31 23:11
the clearing up is not surprising, since the plugin removes and re-creates the socket on restart.

**Comment by timcharper** [comment] 2016-03-31 23:51
After restarting the `weaveplugin`, the amount of open socket connections is climbing regardless of whether or not I run the command. I'm working to reproduce in an idle cluster with identical config.

**Comment by timcharper** [comment] 2016-03-31 23:55
Okay, on the host which I've completely rebooted (which had 90,000 open socket connections), the open weave socket connections does not climb if I run the command.

It appears that running a really network intense load on Docker put weave in to a state in which it stops releasing weave socket connections properly, and that state stops manifesting if I reboot the host completely, but does not stop if I just restart the docker plugin.

**Comment by timcharper** [comment] 2016-04-01 00:00
It looks like every time `weaveplugin` outputs a pair of lines to the log, I get another pair of weave socket connections.

```
[root@host43 ~]# docker logs -f weaveplugin &
[root@host43 ~]# netstat -an | grep weave | wc -l
517
[root@host43 ~]# docker run --net=weave  alpine ping registry.weave.local
INFO: 2016/03/31 23:58:12.299620 Create endpoint d576485f4bc56ca209d677c2ae9b969ef84b28ad8e32e0354f8f4ceca3d8f1c4 &{Response:{Err:} Interface:<nil>}
INFO: 2016/03/31 23:58:12.307896 Join endpoint d056851555671a47f4e0b48bc320269b0b97c91374cdb6da4b6c9d7e2d5227b8:d576485f4bc56ca209d677c2ae9b969ef84b28ad8e32e0354f8f4ceca3d8f1c4 to /var/run/docker/netns/73d9724f2608
PING registry.weave.local (10.40.0.6): 56 data bytes
64 bytes from 10.40.0.6: seq=0 ttl=64 time=1.160 ms
64 bytes from 10.40.0.6: seq=1 ttl=64 time=0.243 ms
^C
--- registry.weave.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.243/0.701/1.160 ms
INFO: 2016/03/31 23:58:14.305900 Leave d056851555671a47f4e0b48bc320269b0b97c91374cdb6da4b6c9d7e2d5227b8:d576485f4bc56ca209d677c2ae9b969ef84b28ad8e32e0354f8f4ceca3d8f1c4
INFO: 2016/03/31 23:58:14.339340 Delete endpoint d576485f4bc56ca209d677c2ae9b969ef84b28ad8e32e0354f8f4ceca3d8f1c4
[root@host43 ~]# netstat -an | grep weave | wc -l
521
```

**Comment by timcharper** [comment] 2016-04-01 00:00
Scratch that, I am getting them regardless of whether or not `weaveplugin` outputs lines.

**Comment by rade** [comment] 2016-04-01 00:14
> It appears that running a really network intense load on Docker put weave in to a state in which it stops releasing weave socket connections properly, and that state stops manifesting if I reboot the host completely, but does not stop if I just restart the docker plugin.

If this doesn't clear when restarting the plugin (btw, [above](https://github.com/weaveworks/weave/issues/2119#issuecomment-204166087) you said it did), then it can't possibly be the plugin holding on to them.

**Comment by timcharper** [comment] 2016-04-01 00:20
It absolutely is the docker weave plugin holding on to them. When I restart the docker weave plugin container, it clears all of the connections, but they shortly thereafter resume climbing.

I've even stopped docker completely, and then started it all again. I'm still observing the same behavior.

**Comment by rade** [comment] 2016-04-01 00:22
Ah ok.

We really need a way to reproduce this behaviour outside marathon.

**Comment by timcharper** [comment] 2016-04-01 00:25
Agreed; presently I can't reproduce the behavior inside of marathon, just that if I extrapolate backwards the rate at which these connections have been climbing, it puts us awfully close to the moment we did our akka cluster load test. So, the best I can do is this:

- This state (of leaking weave socket connections) probably happens as a result of intense load
- This state persists beyond a weave plugin restart (although, the leaked connections are reset back to 0)
- This state persists beyond a complete stop and start of docker
- This state is resolved with a full reboot of the host.

**Comment by timcharper** [comment] 2016-04-01 00:26
Is there anything I can do to run weaveplugin with increased logging levels?

**Comment by rade** [comment] 2016-04-01 00:30
`weave launch --log-level=debug`

Other things to check when you see the problematic behaviour...

`weave status` (pls post the output here)

`sudo kill -QUIT $(docker inspect -f '{{.State.Pid}}' weaveplugin)`

and then capture the stacktrace that appears in `docker logs weaveplugin` and post it somewhere.

**Comment by timcharper** [comment] 2016-04-01 00:57
```
[root@host43 ~]# weave status

        Version: 1.4.6

        Service: router
       Protocol: weave 1..2
           Name: ee:b9:a6:72:93:ae(host43.domain.com)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 6
    Connections: 6 (5 established, 1 failed)
          Peers: 6 (with 30 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.32.0.0-10.47.255.255
  DefaultSubnet: 10.32.0.0/12

        Service: dns
         Domain: weave.local.
       Upstream: 172.30.31.51, 172.30.11.41, 172.30.11.42
            TTL: 1
        Entries: 24

        Service: proxy
        Address: unix:///var/run/weave/weave.sock

        Service: plugin
     DriverName: weave
```

**Comment by timcharper** [comment] 2016-04-01 00:59
```
sudo kill -QUIT $(docker inspect -f '{{.State.Pid}}' weaveplugin)
```

log output: https://gist.github.com/timcharper/44759ce7a1967d0a913996186a2d09c1

**Comment by timcharper** [comment] 2016-04-01 01:08
docker logs weaveplugin after launched with debug log output:

https://gist.github.com/timcharper/cffb32a1d6826d233aa4851e4a2b2ec0

**Comment by rade** [comment] 2016-04-01 07:01
This does rather look like a docker bug to me. The plugin has a bunch of open connections on which it is waiting to receive data. It's the responsibility of the "client", i.e. docker, to close the connections.

**Comment by bboreham** [comment] 2016-04-01 15:41
I can recreate this:

````
$ docker volume ls
DRIVER              VOLUME NAME
local               aa1cd35d7ef2c76644e5590ff26f023a4a7fa79278942b565ac505fe5e539d74
$ netstat | grep weave
unix  3      [ ]         STREAM     CONNECTED     30951    /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     30953    /run/docker/plugins/weavemesh.sock
$ docker volume ls
DRIVER              VOLUME NAME
local               6d7d482a8a80dc1245b9278cb9d69853f1950d9590e2ba45c3412bbab0c1862b
$ netstat | grep weave
unix  3      [ ]         STREAM     CONNECTED     30985    /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     30951    /run/docker/plugins/weave.sock
unix  3      [ ]         STREAM     CONNECTED     30987    /run/docker/plugins/weavemesh.sock
unix  3      [ ]         STREAM     CONNECTED     30953    /run/docker/plugins/weavemesh.sock
````

**Comment by bboreham** [comment] 2016-04-01 16:40
Looks like this was fixed in https://github.com/docker/docker/pull/20686;
my recreation doesn't happen in Docker 1.11.0-rc2.

**Comment by timcharper** [comment] 2016-04-01 16:41
Wonderful! Thank you @bboreham !

**Closed by bboreham** 2016-04-01 16:40 UTC
