### ISSUE TITLE
Docker Swarm requires Weave status to be run

### ISSUE THREAD

**Issue by dwest-lab49** [weaveworks/weave#2306] opened 2016-05-20 12:04 UTC
Hi,

I have setup Docker Swarm in a multi host environment, using WeaveNet, and joining nodes to the Swarm advertising the Weave Proxy port 12357.

For example:

`docker run -d swarm join --advertise 10.0.0.222:12375 consul://10.0.0.111:8500`

The Weave Proxy itself has been launched with:

`weave launch-proxy -H tcp://0.0.0.0:12375`

Upon running `docker info` on a Swarm Manager, each node shows a status of pending.

For example:

`swarm-node-222:12375
  └ ID: XXX
  └ Status: Pending`

To resolve the pending status, I run `weave status`, and the status changes to healthy.

For example:

`swarm-node-222:12375
  └ ID: XXX
  └ Status: Healthy`

Am I missing something? this is manageable when provisioning nodes, however upon restart of a node the status reverts to pending until weave status is run once again.

**Comment by awh** [comment] 2016-05-20 13:03
Thanks for the report @dwest-lab49. Could you let us know versions of Docker, Weave & Swarm?.

**Comment by dwest-lab49** [comment] 2016-05-20 13:08
Docker: 1.11.1
Swarm: 1.2.2
Weave: 1.5.1

Thank you for the prompt response @awh

**Comment by pidster** [comment] 2016-05-20 14:56
@dwest-lab49 is there an error section of the docker info output?

    └ Error: ???

**Comment by dwest-lab49** [comment] 2016-05-20 15:00
The error section is (none). The only difference is the status.

`└ Error: (none)`

**Comment by awh** [comment] 2016-05-23 13:30
@dwest-lab49 reproduced - very strange! Investigation in progress.

**Comment by dwest-lab49** [comment] 2016-05-23 13:32
Thanks for the update @awh

**Comment by awh** [comment] 2016-05-24 07:33
@dwest-lab49 this was caused by the proxy failing to flush response headers for a `GET /1.23/events` from the Swarm master in a timely fashion. Any action that generated Docker events (such as `weave status`, but even running up an arbitrary container directly against the engine would work) would cause the header to be flushed, which is needed by Swarm to transition the node to a healthy state.

Many thanks for the report! This will be in the next bugfix release (1.5.2).

**Comment by dwest-lab49** [comment] 2016-05-24 08:26
Thank you Adam, much appreciated. I look forward to the bugfix release.

**Closed** 2016-05-24 08:27 UTC
