### ISSUE TITLE
TestPaxos "Consensus mismatch" failure

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2132] opened 2016-04-06 06:28 UTC
From https://circleci.com/gh/weaveworks/weave/5272

```
--- FAIL: TestPaxos (15.81s)

    paxos_test.go:311: Consensus mismatch
```

I don't recall _ever_ seeing a failure in TestPaxos. And the code has changed very little since it was written. @awh @dpw

**Comment by dpw** [comment] 2016-04-06 07:45
I assume it's a one-off?

That test does crude fuzz testing, generating random test cases.  So it is possible that it hit some very hard to reproduce bug (though it might be a bug in the harness rather than the paxos code).

(Or there's a bug in the go runtime, or the machine got hit by a cosmic ray, etc.)

To have a chance of finding the cause of such errors, you need to uncomment the `dump` line before the `Fatal` call to dump the paxos state.  I can't remember why I left the `dump` calls commented out.  The output is voluminous, but on the other hand, it should never appear except when it is wanted.

So my suggestion is to uncomment the `dump` lines and wait until this happens again, if it ever does.

**Comment by rade** [comment] 2016-04-06 07:57
> I assume it's a one-off?

yes.

> So my suggestion is to uncomment the `dump` lines 

2e3108781873e2a61ed5b99b948d4399428c9150

**Comment by bboreham** [comment] 2017-02-08 12:06
10 months with no repeat - closing

**Closed by bboreham** 2017-02-08 12:06 UTC
Labels: bug
