### ISSUE TITLE
Kubernetes 1.5 => 1.6 upgrade

### ISSUE THREAD

**Issue by Bregor** [weaveworks/weave#2882] opened 2017-04-04 17:25 UTC
Primary Slack discussion: https://weaveworks.slack.com/archives/C0CGALD7B/p1491324351372830

#### Kubernetes:
```
# kubectl version --short
Client Version: v1.6.1
Server Version: v1.6.1
```

#### Weave-net:
```
# kubectl get ds -n kube-system weave-net -o jsonpath='{.spec.template.spec.containers[*].image}'
weaveworks/weave-kube:1.9.4 weaveworks/weave-npc:1.9.4
```

#### Cluster role and rolebinding:
```
# kubectl get clusterrole,clusterrolebinding|grep weave
clusterroles/weave-net                                      3h

clusterrolebindings/weave-net                                      3h
```

#### Service cluster IP range:
```
# ps aux|grep [k]ube-apiserver|grep -Eo 'service-cluster-ip-range=[0-9.]+'
service-cluster-ip-range=10.33.0.0
```

#### IP alloc range:
```
# kubectl get ds -n kube-system weave-net -o jsonpath='{.spec.template.spec.containers[0].env}'
[map[name:IPALLOC_RANGE value:10.32.0.0/16] map[name:LISTEN_ON valueFrom:map[fieldRef:map[apiVersion:v1 fieldPath:spec.nodeName]]]]
```

#### Routes on host:
```
# ip r | grep 10.3
10.32.0.0/16 dev weave  proto kernel  scope link  src 10.32.64.0
10.33.0.0/16 dev eth1  scope link
```

#### Test from host:
```
# curl -k -H 'Authorization: Bearer <token>' https://10.33.0.1/healthz
ok
```

#### Logs from random pod:
```
# kubectl logs --tail=5 -n kube-system kube-dns-3075034402-zr69j -c kubedns
E0404 16:41:19.494896       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.33.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.33.0.1:443: connect: network is unreachable
E0404 16:41:19.494896       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.33.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.33.0.1:443: connect: network is unreachable
E0404 16:41:19.495065       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: Get https://10.33.0.1:443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-dns&resourceVersion=0: dial tcp 10.33.0.1:443: connect: network is unreachable
I0404 16:41:19.956035       1 dns.go:174] DNS server not ready, retry in 500 milliseconds
```
#### CNI config:
```
# cat /etc/cni/net.d/10-weave.conf
{
    "name": "weave",
    "type": "weave-net"
}
```
#### Routes in pod:
```
# nsenter -t 32473 -n ip r
10.32.0.0/16 dev eth0  proto kernel  scope link  src 10.32.64.1
```

**Comment by marccarre** [comment] 2017-04-05 16:43
@Bregor, would you be able to share the steps to replicate your setup?
In particular,
1. how did you setup your 1.5 cluster? using `kubeadm`?
2. how did you upgrade your 1.5 cluster to 1.6?

Also, do you know after which event did the four IP addresses mentioned at https://weaveworks.slack.com/archives/C0CGALD7B/p1491326098072238 appear?

**Comment by Bregor** [comment] 2017-04-05 20:28
@marccarre 
1. nope, with my homebrewed chef cookbook
2. long story short: download new binaries, modify systemd units, restart. This particular procedure works fine from 1.0 to 1.5.

Four IPs appeared as a result of 

    CNI_COMMAND=ADD CNI_CONTAINERID=ebf545d4a6b0e16c8b1633178fab280ec1f3b5c66e888b639751634451c47161 CNI_IFNAME=eth0 CNI_NETNS=/proc/32473/ns/net CNI_PATH=/opt/cni/bin /opt/cni/bin/weave-net < /etc/cni/net.d/10-weave.conf

**Comment by rade** [comment] 2017-04-10 22:00
@marccarre what is happening with this?

**Comment by marccarre** [comment] 2017-04-11 10:18
@rade, I believe @brb started to investigate it (hence the label), but he is on PTO this week.
I will have a closer look and try to reproduce it today. Lack of details are likely to make this difficult though.

**Comment by bboreham** [comment] 2017-06-01 13:29
Looking through this again, I see the "network unreachable" symptom is in the context of trying to contact the Kubernetes api-server.  The 10.33.0.1 address ought to be remapped to the host address, so either (a) that remapping wasn't happening or (b) the remapped address was genuinely unreachable.

However you also show `curl https://10.33.0.1/healthz` working on the host.

If you can recreate this I'd like to see a `tcpdump` of the failing conversation, ideally on devices `weave`, `eth1` and wherever the host's default route goes.

I'm pretty confused about the "four IPs" symptom; I cannot see how that could happen in the `weave-net` CNI plugin because it's hard-coded to return exactly one address.

**Comment by bboreham** [comment] 2017-07-19 22:52
I think we have to close this due to lack of information and time passing.

**Closed by bboreham** 2017-07-19 22:52 UTC
Labels: state/investigating
