### ISSUE TITLE
Network config CNI plugin for kuberne​tes

### ISSUE THREAD

**Issue by guillelb** [weaveworks/weave#3005] opened 2017-06-05 09:05 UTC
I was using Flannel as network layer of kubernetes v1.6.1, but I need **multicast** functionality, then I am trying to work with weave net.

My k8s installation is from scratch, launching kubelet and kube-proxy binaries as Linux services.

**Weave version**:
- weave script 1.9.5
- weave router 1.9.5
- weave proxy  1.9.5
- weave plugin 1.9.5

**Docker version**:
- Version:      1.12.6
- API version:  1.24
- Go version:   go1.6.2
- Git commit:   78d1802

**uname -a** (Ubuntu 16.04.2 LTS):
- Linux k8sVAmaster1x6 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**K8S version**:
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

 

I deploy **weave net** as **CNI plugin**, as described in the documentation:
https://www.weave.works/docs/net/latest/cni-plugin/

`weave launch 192.168.215.7 --ipalloc-range 172.24.30.0/24`
`eval $(weave env)`

The weave config file is created by `weave setup`:

`# cat /etc/cni/net.d/10-weave.conf`
`{`
`    "name": "weave",`
`    "type": "weave-net"`
`}`

When I launch **kubelet**, everything seems to work perfectly, without errors, with the params: 

`--network-plugin=cni --network-plugin-dir=/etc/cni/net.d`

I note one difference between launch the same docker image from K8S and launch from docker:
- 3 **Interfaces**(launched with **Docker** `docker run -ti busybox sh`):
`# ip addr show`

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1`
   ` link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00`
  `  inet 127.0.0.1/8 scope host lo`
   `    valid_lft forever preferred_lft forever`
   ` inet6 ::1/128 scope host `
   `    valid_lft forever preferred_lft forever`

`42: eth0@if43: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue `
   ` link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff`
    `inet 172.17.0.2/16 scope global eth0`
     `  valid_lft forever preferred_lft forever`
    `inet6 fe80::42:acff:fe11:2/64 scope link `
   `    valid_lft forever preferred_lft forever`

`44: ethwe@if45: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1376 qdisc noqueue `
   ` link/ether ae:f1:d2:92:7c:90 brd ff:ff:ff:ff:ff:ff`
 `   inet 172.24.30.129/24 scope global ethwe`
  `     valid_lft forever preferred_lft forever`
   ` inet6 fe80::acf1:d2ff:fe92:7c90/64 scope link `
    `   valid_lft forever preferred_lft forever`

- 2 **Interfaces**(launched with **Kubernetes** `kubectl run -i --tty busybox18 --image=busybox -- sh`):

`# ip addr show`

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1`
   ` link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00`
 `   inet 127.0.0.1/8 scope host lo`
 `      valid_lft forever preferred_lft forever`
 `   inet6 ::1/128 scope host `
 `      valid_lft forever preferred_lft forever`

`15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1376 qdisc noqueue `
 `   link/ether 36:53:c3:03:26:d1 brd ff:ff:ff:ff:ff:ff`
  `  inet 172.24.30.1/24 scope global eth0`
 `      valid_lft forever preferred_lft forever`
 `   inet6 fe80::3453:c3ff:fe03:26d1/64 scope link `
`       valid_lft forever preferred_lft forever`

- Routing table (In the **Docker** container):
`# route`

`Kernel IP routing table`
`Destination     Gateway         Genmask         Flags Metric Ref    Use Iface`
`default         172.17.0.1      0.0.0.0         UG    0      0        0 eth0`
`172.17.0.0       *               255.255.0.0     U     0      0        0 eth0`
`172.24.30.0     *               255.255.255.0   U     0      0        0 ethwe`
`224.0.0.0         *               240.0.0.0       U     0      0        0 ethwe`

- Routing table (In the **Kubernetes** container):

`# route`
`Kernel IP routing table`
`Destination     Gateway         Genmask         Flags Metric Ref    Use Iface`
`default         172.24.30.3     0.0.0.0         UG    0      0        0 eth0`
`172.24.30.0     *               255.255.255.0   U     0      0        0 eth0`

**Everything** (ping, telnet,... inside and outside the cluster) work correctly between PODs, but the MULTICAST traffic is not working.

**_Questions:_**

1. Do I need some other configuration in the  `weave.conf ` file?
2. Why K8S doesn't create all the same interfaces in the container?
3. Is there some simple example to test if MULTICAST traffic works?

**Comment by bboreham** [comment] 2017-06-05 10:00
2. Kubernetes only understands one network per pod; also it insists that the device is called `eth0`.  This is actually the same as `ethwe` in the other container; just we set a default route on that device.

However I think the reason it's not working is we don't have the equivalent of the route `224.0.0.0 * 240.0.0.0 U 0 0 0 ethwe`.  I'm just going to check now.

**Comment by bboreham** [comment] 2017-06-05 10:14
I take that back; we don't need that route because the default route goes via the weave bridge.

So I tried using a [small demo I hacked together](https://github.com/bboreham/mballs/tree/mweb); each process sends out a multicast packet every second and notes which ones it has received:

    $ kubectl run mweb --image=bboreham/mweb --replicas=3 -- --iface=eth0

then I find one of the IP addresses of those pods:

```
$ kubectl --kubeconfig /etc/kubernetes/admin.conf get pods -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP          NODE
mweb-4005489796-4sm5q      1/1       Running   0          6m        10.38.0.3   brya-2
mweb-4005489796-s5vlb      1/1       Running   0          6m        10.32.0.4   brya-1
mweb-4005489796-t8wrj      1/1       Running   0          6m        10.32.0.5   brya-1
```

then I ask it who it's heard from:

```
$ curl 10.32.0.4:8080
mweb-4005489796-4sm5q 10.38.0.3:51164
mweb-4005489796-s5vlb 10.32.0.4:59870
mweb-4005489796-t8wrj 10.32.0.5:54567
```

**Comment by marccarre** [comment] 2017-06-06 11:28
Hi @guillelb, did the above help and answered all your questions?
I had a quick try against Kubernetes 1.6.1 (set up using [`kubeadm`](https://kubernetes.io/docs/admin/kubeadm/)) and Weave Net 1.9.5 (set up using [these recommended instructions](https://www.weave.works/docs/net/latest/kube-addon/)), and definitely could get multicast working:
```
host1$ kubeadm init --kubernetes-version=v1.6.1
host2$ kubeadm join --token <token> 10.128.0.6:6443
host1$ kubectl apply -n kube-system -f https://github.com/weaveworks/weave/releases/download/v1.9.5/weave-daemonset-k8s-1.6.yaml
host1$ kubectl run mweb --image=bboreham/mweb --replicas=3 -- --iface=eth0
host1$ kubectl get po -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP          NODE
mweb-4005489796-3mbl1   1/1       Running   0          14s       10.40.0.2   host1
mweb-4005489796-hmqhr   1/1       Running   0          14s       10.38.0.1   host2
mweb-4005489796-n446s   1/1       Running   0          14s       10.38.0.2   host2
host1$ curl 10.40.0.2:8080
mweb-4005489796-n446s 10.38.0.2:57113
mweb-4005489796-hmqhr 10.38.0.1:58962
mweb-4005489796-3mbl1 10.40.0.2:40211
```

**Comment by marccarre** [comment] 2017-06-06 15:13
FYI @guillelb, I was also able to get it working with a setup closer to yours, following the same [CNI plugin instructions](https://www.weave.works/docs/net/latest/cni-plugin/) you did. Not sure if this can be useful to you, but below are the detailed steps.
Assuming 3 hosts, `host0`, `host1` and `host2`:

```
host0|1|2$ curl -L https://github.com/weaveworks/weave/releases/download/v1.9.5/weave -o /usr/local/bin/weave && \
  chmod a+x /usr/local/bin/weave && \
  mkdir -p /opt/cni/bin && \
  mkdir -p /etc/cni/net.d && \
  weave setup && \
  ls -l /etc/cni/net.d/*weave* && \
  ls -l /opt/cni/bin/*weave*

host0$ weave launch --ipalloc-range 172.24.30.0/24
host1$ weave launch --ipalloc-range 172.24.30.0/24 10.128.0.6
host2$ weave launch --ipalloc-range 172.24.30.0/24 10.128.0.5 10.128.0.6

host0$ weave status connections
<- 10.128.0.5:35183      established fastdp da:76:99:a4:e0:91(host1) mtu=1376
<- 10.128.0.4:48003      established fastdp aa:14:2a:5b:e2:f3(host2) mtu=1376
host1$ weave status connections
-> 10.128.0.6:6783       established fastdp 42:8e:e8:c4:52:1b(host0) mtu=1376
<- 10.128.0.4:42587      established fastdp aa:14:2a:5b:e2:f3(host2) mtu=1376
host2$ weave status connections
-> 10.128.0.5:6783       established fastdp da:76:99:a4:e0:91(host1) mtu=1376
-> 10.128.0.6:6783       established fastdp 42:8e:e8:c4:52:1b(host0) mtu=1376

host0|1|2$ vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --network-plugin-dir=/etc/cni/net.d --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS

host0|1|2$ systemctl daemon-reload
host0$ systemctl restart kubelet && sleep 3 && kubeadm init --kubernetes-version=v1.6.1
host1|2$ systemctl restart kubelet && sleep 3 && kubeadm join --token 5fc0fc.dabfa82a02b98100 10.128.0.6:6443

host0|1|2$ ps -elf | grep /usr/bin/kubelet
### Checked added flags were picked up.

host0$ kubectl get po --all-namespaces
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   etcd-host0                       1/1       Running   0          1m
kube-system   kube-apiserver-host0             1/1       Running   0          1m
kube-system   kube-controller-manager-host0    1/1       Running   0          14s
kube-system   kube-dns-3913472980-13p5c        3/3       Running   0          1m
kube-system   kube-proxy-2t29z                 1/1       Running   0          1m
kube-system   kube-proxy-pllq8                 1/1       Running   0          30s
kube-system   kube-proxy-qpc8b                 1/1       Running   0          31s
kube-system   kube-scheduler-host0             1/1       Running   0          1m

host0$ kubectl get nodes
NAME      STATUS    AGE       VERSION
host0    Ready     1m        v1.6.1
host1    Ready     50s       v1.6.1
host2    Ready     49s       v1.6.1

host0$ kubectl run mweb --image=bboreham/mweb --replicas=3 -- --iface=eth0
host0$ kubectl get po -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP              NODE
mweb-4005489796-hprmg   1/1       Running   0          6s        172.24.30.64    host2
mweb-4005489796-n9wfc   1/1       Running   0          6s        172.24.30.192   host1
mweb-4005489796-v1w8l   1/1       Running   0          6s        172.24.30.193   host1

host2$ curl 172.24.30.64:8080
mweb-4005489796-hprmg 172.24.30.64:59400
mweb-4005489796-n9wfc 172.24.30.192:47462
mweb-4005489796-v1w8l 172.24.30.193:59198
```

I am closing this issue for now as I believe we have answered all of your questions, and we weren't able to reproduce the issue you had, but feel free to reopen if you think we're missing something or if you have any other question :slightly_smiling_face:

**Closed by marccarre** 2017-06-06 15:13 UTC
Labels: question

**Comment by guillelb** [comment] 2017-06-06 16:30
Thank you, my questions have been solved.
Multicast works properly without any other configuration, and I realized thank kubernetes works with only one  interface on each POD.
