### ISSUE TITLE
disabling dns

### ISSUE THREAD

**Issue by hd-deman** [weaveworks/weave#1687] opened 2015-11-15 22:01 UTC
`weave launch-router $ips`
but it still run with dns
```
docker logs weave
INFO: 2015/11/15 19:24:27.242122 Command line options: map[docker-api:unix:///var/run/docker.sock dns-listen-address:172.17.0.1:53 http-addr:127.0.0.1:6784 ipalloc-range:10.32.0.0/12 datapath:weave dns-effective-listen-address:172.17.0.1 iface:veth-weave name:xx:xx:xx:xx:xx:80 nickname:johnny-cage port:6783]
INFO: 2015/11/15 19:24:27.242291 Command line peers: [52.29.xxx.xxx 52.29.xxx.xxx 52.29.xxx.xxx 52.29.xxx.xxx 52.28.xxx.xxx]
INFO: 2015/11/15 19:24:27.244608 Communication between peers is encrypted.
INFO: 2015/11/15 19:24:27.245543 Our name is xx:xx:xx:xx:xx:80(johnny-cage)
INFO: 2015/11/15 19:24:27.265093 [docker] Using Docker API on unix:///var/run/docker.sock: &[Version=1.9.0 ApiVersion=1.21 GitCommit=76d6bc9 GoVersion=go1.4.2 Os=linux Arch=amd64 KernelVersion=4.2.0-16-generic BuildTime=Tue Nov  3 17:54:53 UTC 2015]
INFO: 2015/11/15 19:24:27.265262 Assuming quorum size of 4
FATA: 2015/11/15 19:24:27.265983 Unable to start dns server: listen udp 172.17.0.1:53: bind: address already in use
```

**Comment by hd-deman** [comment] 2015-11-15 23:32
solved by `weave launch-router --no-dns $PEERS`

and `--no-dns`missed in usage docs
```
weave --help
Usage:

weave --help | help
weave setup
weave version
weave launch        [--password <password>] [--nickname <nickname>]
                      [--ipalloc-range <cidr> [--ipalloc-default-subnet <cidr>]]
                      [--no-discovery] [--init-peer-count <count>] <peer> ...
weave launch-router [--password <password>] [--nickname <nickname>]
                      [--ipalloc-range <cidr> [--ipalloc-default-subnet <cidr>]]
                      [--no-discovery] [--init-peer-count <count>] <peer> ...
```

**Comment by bboreham** [comment] 2015-11-15 23:35
Yes, it does this by default. 

There is an (undocumented) `--no-dns` option to `weave launch-router` that will stop it.

**Comment by rade** [comment] 2015-11-15 23:39
@hd-deman *why* do you want to disable DNS?

**Comment by rade** [comment] 2015-11-15 23:46
> @hd-deman why do you want to disable DNS?

btw, I am asking because the reason the `--no-dns` option is undocumented is because we cannot think of a reason why anybody would want to disable weaveDNS. So if you can tell us what the reason is then we can update our docs.

**Comment by hd-deman** [comment] 2015-12-18 11:39
@rade because I'm using consul as dns

**Comment by bboreham** [comment] 2015-12-18 16:13
@hd-deman does having WeaveDNS running prevent you from doing that?  If so, what are the symptoms?

**Comment by hd-deman** [comment] 2015-12-24 23:18
@bboreham no. I just have working stack witch I using with weave network.

**Comment by rade** [comment] 2016-03-28 09:23
Another user has [come up(https://twitter.com/lawouach/status/714365688043945984) with a plausible reason for wanting to disable DNS: if you are trying to run your own DNS server on the host, which port-clashes with weaveDNS.

Though note that resolving #1891 would be a better way of dealing with this.

**Closed** 2016-03-28 11:53 UTC
Labels: [component/dns], [component/docs]

**Comment by rade** [comment] 2016-03-28 11:55
Doc changes are live. See the last sentence of the [weaveDNS intro](http://docs.weave.works/weave/latest_release/weavedns.html#usage).

Usage change will go into the next release.

**Comment by jacknlliu** [comment] 2017-07-10 01:43
I got this error with `weave v2.0.1`. This problem caused by conflicted with `dnsmasq` on host from my usage. Any good solution for this?

**Comment by bboreham** [comment] 2017-07-10 13:34
@jacknlliu did you add the `--no-dns` flag?  Or you are asking for an alternative solution?

**Comment by jacknlliu** [comment] 2017-07-10 13:45
I hope an alternative solution. `dns` should be shipped.

**Comment by bboreham** [comment] 2017-07-11 11:37
The underlying problem is that only one program can listen on port 53 on a given interface. You are running `dnsmasq` which, I would guess, is listening on 0.0.0.0 which means "all interfaces", so WeaveDNS is locked out. 

If you can configure `dnsmasq` to not listen on the `docker` bridge then WeaveDNS will be able to work.

**Comment by rade** [comment] 2017-07-11 11:39
See #1891 for addressing this on the Weave Net side.

**Comment by jacknlliu** [comment] 2017-07-12 00:45
For future readers, if you use `dnsmasq` as your DNS server, edit `/etc/dnsmasq.conf` file, and set the following options
```
except-interface=docker0

no-dhcp-interface=docker0

bind-interfaces
```
And then restart `dnsmasq`
```
$ sudo systemctl restart dnsmasq
```
Then `weave launch` will be able to work.

**Comment by bboreham** [comment] 2017-07-12 00:54
@jacknlliu thanks for posting the follow-up; good to hear you got it working
