### ISSUE TITLE
[Query]Can weave be used to get IPV6 address for Pod

### ISSUE THREAD

**Issue by bsshetty** [weaveworks/weave#3374] opened 2018-08-10 11:32 UTC
This is a query, I would like to know if weave supports getting IPV6 address for Pod. If so, is there any documention on steps to follow, thanks

**Comment by bboreham** [comment] 2018-08-10 12:04
Sorry, no support for IPv6 at present.  

Closing as duplicate of #19

**Closed by bboreham** 2018-08-10 12:04 UTC
