### ISSUE TITLE
Kubernetes Weave networking with container started outside Kubernetes: port filtered

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2715] opened 2016-12-27 21:29 UTC
This is the same scenario as described in https://github.com/weaveworks/weave/issues/2714:

Setup: Kubernetes/Weave, 1 master, 3 slaves.

One container (named crc) is started outside Kubernetes. The crc is started on slave 1 with: ``sudo docker run -d --mac-address=xx:xx:xx:xx:xx:xx --name crc -p 8989:8989 imagename``. 

3 containers are started as a pod via kubectl.

If the pod is scheduled on slave 1, a connect of each container in the pod to the crc fails. Port 8989 is filtered. Running nmap from one of the containers in the pod:
````
~/application # nmap -n -p 8900-9000 10.10.10.51

Starting Nmap 7.01 ( https://nmap.org ) at 2016-12-27 21:10 UTC
Nmap scan report for 10.10.10.51
Host is up (0.00011s latency).
Not shown: 100 closed ports
PORT     STATE    SERVICE
8989/tcp filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 3.81 seconds
````

If the pod is scheduled on slave 3, a connect of each container in the pod to the crc succeeds. Port 8989 is open. Running nmap from one of the containers in the pod:

````
~/lrc #  nmap -n -p 8900-9000 10.10.10.51

Starting Nmap 7.01 ( https://nmap.org ) at 2016-12-27 21:18 UTC
Nmap scan report for 10.10.10.51
Host is up (0.00042s latency).
Not shown: 100 closed ports
PORT     STATE SERVICE
8989/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 1.94 seconds
````

Also running the crc at e.g. port 40000 did not make a difference. See below.

If the pod is scheduled on slave 1 and I use netcat from one of the containers in the pod, I get:

````
[root@kub-minion1 bergtwvd]# docker exec -it dcfe563f94f3 sh
~/lrc # nc -z -v -w1 10.10.10.51 40000
nc: 10.10.10.51 (10.10.10.51:40000): Operation timed out
~/lrc #
````

If I instead start to a container (using the same docker image) directly, I get:
````
[root@kub-minion1 bergtwvd]# docker run -it --rm --entrypoint=sh imagename
~/lrc #  nc -z -v -w1 10.10.10.51 40000
10.10.10.51 (10.10.10.51:40000) open
~/lrc #
````

Seems that Kubernetes/Weave networking on the same host blocks ports.

**Comment by bboreham** [comment] 2017-01-03 11:39
I believe this is caused by the same iptables rule described at https://github.com/weaveworks/weave/issues/2714#issuecomment-270096815

**Comment by awh** [comment] 2017-01-04 09:56
Duplicate of #2714.

**Closed by awh** 2017-01-04 09:56 UTC
Labels: bug, resolution/duplicate
