### ISSUE TITLE
Weave IPAM CNI plugin cannot distinguish between empty and nil routes

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#3331] opened 2018-06-17 10:28 UTC
Consider the following CNI config:

```
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true,
    "ipam": {
       "type": "weave-ipam",
       "subnet": "10.44.3.0/24"
    }
}
```

When using the config, expected behavior is that the Weave CNI plugin will add a default route as can be seen [here](https://github.com/weaveworks/weave/blob/v2.3.0/plugin/net/cni.go#L145). However, the IPAM plugin [populates](https://github.com/weaveworks/weave/blob/v2.3.0/plugin/ipam/cni.go#L60) the `Routes` field with empty list, so the default route is not added.

**Comment by psaini79** [comment] 2018-06-19 06:58
I tried following and it works. Let me know if you see any issue in using weave with following approach:

I tried following conf and it worked. I am getting correct route settings.

{
"name": "weave",
"type": "weave-net",
"hairpinMode": true,
"ipam": {
"type": "host-local",
"subnet": "192.168.16.0/24",
"rangeStart": "192.168.16.201",
"rangeEnd": "192.168.16.225",
"routes": [
{ "dst": "0.0.0.0/0" }
]
}
}

**Comment by psaini79** [comment] 2018-06-19 06:59
The only part on my every worker node, I have to modify weave conf file manually based on different ranges.

**Comment by bboreham** [comment] 2018-06-19 08:17
I think the net plugin is behaving as designed and the Weave Net ipam shouldn’t populate an empty list. 

Is it actually the ipam plugin, or libcni that is adding an empty list?

**Comment by murali-reddy** [comment] 2018-07-27 11:13
So i digged in bit more.
It turns out the source of the problem is the network configuration not having a CNI version. Example config shared in #3331 does not have a `cniVersion` explicitly specified. Which is [interpreted](https://github.com/containernetworking/cni/blob/master/pkg/version/conf.go#L34) by CNI library as `0.1.0`

When weave-net plugin invokes IPAM plugin using libcni helper functions it will result in `0.2.0` result as 0.2.0 supports cniVersion 0.1.0.

Weave CNI plugin converts the results to current version of the result using libcni helper function [`convertFrom020` ](https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L68) which initializes the Routes with zero-length slice irrespective of any routes in the config. If we specify `0.3.0` as `cniVerson` there is no issue.

I think libcni should not be creating empty slice of routes when there are no routes specified in the network configuration.

@bboreham @brb Any thoughts? I can open an issue libcni

**Comment by bboreham** [comment] 2018-07-27 11:18
@murali-reddy that's great: I really like to understand what is going wrong before fixing things.

A quick glance suggests that libcni is indeed initializing that member unnecessarily.

We should add the CNI version to our standard config, right?  And maybe mention this in the docs.

**Comment by brb** [comment] 2018-07-28 13:09
@murali-reddy Good investigation! Please file an issue for libcni.

**Comment by murali-reddy** [comment] 2018-07-30 10:17
> We should add the CNI version to our standard config, right? And maybe mention this in the docs.

Default config that weave creates already sets `cniVersion` to 0.3.0.  But even if users create custom config IMO this is something better fixed by libcni. If its not for 0.3.0, it might happen for 0.4.0

> I really like to understand what is going wrong before fixing things.

Basically the problem (i.e. adding empty slice of Routes) is manifesting when converting IPAM plugin result to `current` version IPAM result. Opened https://github.com/containernetworking/cni/issues/573

**Comment by murali-reddy** [comment] 2018-07-31 07:33
I will close this issue and follow up on the libcni issue. Please reopen if you think otherwise.

**Closed by murali-reddy** 2018-07-31 07:33 UTC
Labels: [component/plugin], bug
