### ISSUE TITLE
bug: kubernetes delete all weave pods cause duplicate IPs for differenetes pods

### ISSUE THREAD

**Issue by peiqi-caicloud** [weaveworks/weave#2719] opened 2017-01-05 05:52 UTC
we use weave to provide networking service for kubernetes;

when we use kubectl delete pod --all --namespace=kube-system; It can easily cause duplicate IPs allocation. e.x: 192.168.67.0 for two different pods. 

after we delete one of the duplicated pods; the status of weave pod will recover to running from CrashBackOff.

We think this is a bug in IPAM, which may lack considering of IP allocation sync after weave restart.

**Comment by bboreham** [comment] 2017-01-05 10:02
I think this is a duplicate of #2610.

Could you say a bit more about what prompted you to delete all the pods and/or why you expected things to work fine after you did that?

**Comment by bboreham** [comment] 2017-01-06 10:29
I'm going to add a warning to the docs.

**Closed** 2017-01-09 15:49 UTC
Labels: resolution/duplicate, [component/docs]
