### ISSUE TITLE
weave net for windows?

### ISSUE THREAD

**Issue by messmerxx** [weaveworks/weave#3194] opened 2017-12-02 11:37 UTC
i think somebody has raised the issue. but i did not get the clear answer yet.

Does weave net can be supported on windows server 2016??

thank you very much for your reply.

best regards,
Kejun Xu

**Comment by bboreham** [comment] 2017-12-02 15:01
Weave Net is currently Linux-only. 

Closing as duplicate of #976

**Closed by bboreham** 2017-12-02 15:01 UTC
