### ISSUE TITLE
Weave goes ape sh!t on Apache Spark cluster, CPU resource @ 105%, Mem @ 96.8%

### ISSUE THREAD

**Issue by crockpotveggies** [weaveworks/weave#2297] opened 2016-05-14 20:41 UTC
Currently operating an 8-node cluster in a dedicated hardware environment. Weave goes crazy with the amount of data going in and out of each node (currently doing neural network training). Physical network is using a CISCO SG200-50 switch, which is normally enough to handle Apache Spark data volume.

I noticed one of our nodes failed a heartbeat check and started to hang. It also forced the entire Spark cluster to hang since data passing to that specific node kept failing. It would appear Weave is suffering from some sort of overhead problem.

Here's an output from `top`:

![screen shot 2016-05-14 at 1 31 45 pm](https://cloud.githubusercontent.com/assets/1445295/15270571/664b8b06-19d9-11e6-8550-1aac39135e4a.png)

Every node in the cluster is operating on fast datapath:
```
-> 10.0.0.10:6783        established fastdp 12:9e:b7:ab:66:61(ubuntu6)
<- 10.0.0.2:58350        established fastdp a6:00:3c:3a:2b:eb(ubuntu1)
-> 10.0.0.4:6783         established fastdp ee:3d:0f:b7:d4:ef(ubuntu2950)
<- 10.0.0.7:33188        established fastdp ba:d3:b0:aa:0b:0a(ubuntu4)
<- 10.0.0.6:50295        established fastdp e2:be:7c:83:a6:60(ubuntu3)
-> 10.0.0.9:6783         established fastdp a6:0d:c0:29:98:aa(ubuntu5)
<- 10.0.0.5:37182        established fastdp ee:d7:4a:3d:d6:db(ubuntu2)
```

Each node is outfitted with 8 cores and has 16GB of available memory. How can I help further debug this or provide more information so it can be fixed?

**Comment by brb** [comment] 2016-05-16 10:52
Could you provide the following info:

* Do you run Apache Spark inside a Docker container? If yes, what image do you use? How many containers do you run on a single host?
* Docker / Weave versions.
* Full weave log and `weave report` on the failing host.

**Comment by crockpotveggies** [comment] 2016-05-16 17:19
Docker container is a Spark YARN image I've assembled myself here: https://github.com/crockpotveggies/docker-spark

Output from `docker version`:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

Output from `weave version`:
```
weave script 1.5.1
weave router 1.5.1
weave proxy  1.5.1
weave plugin 1.5.1
```

Can't provide a `weave report` since I've shut down Weave and migrated everything to native installation (needed to continue my work). The container isn't up.

`docker logs weave`: https://gist.github.com/crockpotveggies/081be48eaa5ff863026d070f41bc2fc0
`docker logs weaveplugin`: https://gist.github.com/crockpotveggies/9d11a8ed395a42fe84e4e461a4a1d09c
`docker logs weaveproxy`: https://gist.github.com/crockpotveggies/363240f8a3328cf07155c1664f168d47

**Comment by bboreham** [comment] 2016-06-08 11:04
The first errors in the log:

````
ERRO: 2016/05/14 20:26:56.518936 Captured frame from MAC (9a:ae:63:b8:8d:2e) associated with another peer 92:3d:60:2b:ce:d4(ubuntu7)
INFO: 2016/05/14 20:26:56.525877 Discovered remote MAC 32:1f:90:e7:56:5e at 12:9e:b7:ab:66:61(ubuntu6)
ERRO: 2016/05/14 20:26:56.525915 Captured frame from MAC (32:1f:90:e7:56:5e) associated with another peer 12:9e:b7:ab:66:61(ubuntu6)
````

There are a number of similar errors subsequently - 92 over a 2-hour period.

So somehow these packets were being seen on two peers.  Maybe weave is looping them somehow, or maybe the underlying network is routing them?

**Comment by bboreham** [comment] 2016-06-08 11:19
@crockpotveggies I see the underlying network addresses of the peers were `10.0.0.x`; can you say what subnet they were in?  

Weave was using its default for container addresses - `10.32.0.0/12` - so I'm wondering if that range overlapped.  Though we do attempt to check for this situation.

**Comment by crockpotveggies** [comment] 2016-06-09 19:34
Apologies since I've since repurposed the hardware for Flink/Kafka work, but let me print the details of the network here since I don't think the subnet has changed:

On login:
```
  IP address for eth0:            10.0.0.10
  IP address for docker_gwbridge: 172.18.0.1
  IP address for docker0:         172.17.0.1
  IP address for weave:           10.7.255.254
```

and `ifconfig` output:
```
datapath  Link encap:Ethernet  HWaddr 22:eb:e0:04:db:4d
          inet6 addr: fe80::20eb:e0ff:fe04:db4d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:1075 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:782429 (782.4 KB)  TX bytes:648 (648.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:37:b2:2a:1d
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:37ff:feb2:2a1d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7745672 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7908885 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:837837010 (837.8 MB)  TX bytes:5531068714 (5.5 GB)

docker_gwbridge Link encap:Ethernet  HWaddr 02:42:2d:34:24:c1
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:1d:09:67:99:2a
          inet addr:10.0.0.10  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::21d:9ff:fe67:992a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:285373821 errors:0 dropped:56 overruns:0 frame:0
          TX packets:136152046 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:422029616127 (422.0 GB)  TX bytes:24678677714 (24.6 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:336 errors:0 dropped:0 overruns:0 frame:0
          TX packets:336 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:28365 (28.3 KB)  TX bytes:28365 (28.3 KB)

veth0543665 Link encap:Ethernet  HWaddr 8a:7a:d9:2f:ce:de
          inet6 addr: fe80::887a:d9ff:fe2f:cede/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:258 (258.0 B)  TX bytes:2664 (2.6 KB)

veth18b645a Link encap:Ethernet  HWaddr c2:72:e1:21:bd:bb
          inet6 addr: fe80::c072:e1ff:fe21:bdbb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:258 (258.0 B)  TX bytes:2364 (2.3 KB)

veth4214b68 Link encap:Ethernet  HWaddr 1e:cd:b6:dd:cb:52
          inet6 addr: fe80::1ccd:b6ff:fedd:cb52/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:107487 errors:0 dropped:0 overruns:0 frame:0
          TX packets:115539 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:12540257 (12.5 MB)  TX bytes:121121158 (121.1 MB)

veth42a9080 Link encap:Ethernet  HWaddr 36:81:f7:53:9b:ce
          inet6 addr: fe80::3481:f7ff:fe53:9bce/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1115957 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1312232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:95145677 (95.1 MB)  TX bytes:2696152435 (2.6 GB)

veth48c9a6f Link encap:Ethernet  HWaddr c2:de:ce:cb:5b:7b
          inet6 addr: fe80::c0de:ceff:fecb:5b7b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6234605 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6094318 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:816424394 (816.4 MB)  TX bytes:2070867591 (2.0 GB)

veth714c887 Link encap:Ethernet  HWaddr 1a:db:2c:bc:cb:4e
          inet6 addr: fe80::18db:2cff:febc:cb4e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1368 (1.3 KB)  TX bytes:4689 (4.6 KB)

veth77eae56 Link encap:Ethernet  HWaddr b6:79:74:ce:bf:31
          inet6 addr: fe80::b479:74ff:fece:bf31/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:287329 errors:0 dropped:0 overruns:0 frame:0
          TX packets:386643 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:22133393 (22.1 MB)  TX bytes:642857487 (642.8 MB)

vetha77a546 Link encap:Ethernet  HWaddr 72:66:15:53:c7:13
          inet6 addr: fe80::7066:15ff:fe53:c713/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:258 (258.0 B)  TX bytes:906 (906.0 B)

vethwe-bridge Link encap:Ethernet  HWaddr e6:fd:6f:09:ab:fe
          inet6 addr: fe80::e4fd:6fff:fe09:abfe/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:275554299 errors:0 dropped:0 overruns:0 frame:0
          TX packets:139226906 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:389751145765 (389.7 GB)  TX bytes:11772817892 (11.7 GB)

vethwe-datapath Link encap:Ethernet  HWaddr 46:20:57:a1:b1:4f
          inet6 addr: fe80::4420:57ff:fea1:b14f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:139226906 errors:0 dropped:0 overruns:0 frame:0
          TX packets:275554299 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11772817892 (11.7 GB)  TX bytes:389751145765 (389.7 GB)

vethwepl6734 Link encap:Ethernet  HWaddr c6:a9:f4:69:6d:11
          inet6 addr: fe80::c4a9:f4ff:fe69:6d11/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:3999842 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5623164 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:369047372 (369.0 MB)  TX bytes:7429151270 (7.4 GB)

vethwepl7204 Link encap:Ethernet  HWaddr b2:a4:3b:7c:8c:5b
          inet6 addr: fe80::b0a4:3bff:fe7c:8c5b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:1594760 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1979593 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:180232336 (180.2 MB)  TX bytes:2312731374 (2.3 GB)

vethwepl7432 Link encap:Ethernet  HWaddr ca:2b:f0:e6:02:0a
          inet6 addr: fe80::c82b:f0ff:fee6:20a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:1210769 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1334332 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2172560506 (2.1 GB)  TX bytes:452137832 (452.1 MB)

vethwepl7684 Link encap:Ethernet  HWaddr 4e:1f:9a:94:61:1d
          inet6 addr: fe80::4c1f:9aff:fe94:611d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:132421518 errors:0 dropped:0 overruns:0 frame:0
          TX packets:266618227 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:9050976340 (9.0 GB)  TX bytes:379557182091 (379.5 GB)

weave     Link encap:Ethernet  HWaddr 86:98:05:6d:33:6f
          inet addr:10.7.255.254  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::8498:5ff:fe6d:336f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:440 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:19940 (19.9 KB)  TX bytes:690 (690.0 B)
```

**Comment by crockpotveggies** [comment] 2016-06-09 19:35
I'd also note that the network switch connecting all of these machines *supposedly* has loopback protection, but it's possible I didn't configure it properly.

**Comment by bboreham** [comment] 2016-06-10 09:31
OK, scratch my first theory: your hosts were on `10.0.0.0/24` which shouldn't clash.

>  `IP address for weave:           10.7.255.254`

This is odd with `--ipalloc-range=10.32.0.0/12`.  Do you recall how this came about?

It still seems plausible that some sort of feedback loop caused the very high CPU usage; perhaps under that load the garbage collector couldn't run often enough which led to the very high memory usage.  But I cannot put my finger on exactly how.

**Comment by crockpotveggies** [comment] 2016-06-10 15:42
It's possible that the IP allocation is due to a new install of Docker Cloud Agent, which has been placed since I filed this issue and before I made that previous comment. Spark usually incurs heavy load, are there ways to tweak garbage collection? Perhaps there weren't enough resources for the GC to run while Spark was consuming the machine?

**Comment by bboreham** [comment] 2016-06-13 09:30
I don't think that's the right road to go down; Weave should never be creating so much garbage that this is an issue.  Something went very wrong, and we'd love to fix the root cause, but we need some way to recreate it.

**Comment by rade** [comment] 2016-06-20 03:08
I am closing this since we cannot reproduce the problem; if steps to reproduce become available then please re-open.

**Closed by rade** 2016-06-20 03:08 UTC
Labels: bug
