### ISSUE TITLE
trouble routing traffic through the peers to cousin containers; problems upgrading to weave 1.5.1

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2325] opened 2016-05-30 23:05 UTC
My questions are these:

Is it possible for the weave-dns server to manage a zone file other
than weave.local.?

How do I prevent IPAM from creating an address when to preserve legacy
behavior I need to make assignments?

If IPAM must create its own addresses beyond what I need to restore
legacy behavior, what can I do to ensure that happens in a
non-competing network segment?

I am not a Network Engineer and while I understand conceptually
something of what it means to partition a network segment, the
mechanics of how I would use weave to do this still elude me.  

I wonder how it is I would: 
let my physical hosts peer with one another at 10.0.0.0/24, 
while my company's internal assets are hosted at 10.0.1.0/24
and clients sites get smaller segments all inside a 10.0.0.0.20

I am working to upgrade a legacy system running on weave since 2014.  
There is much configuration hard-coded to assume a 10.0.1.0/24 network
segment for the legacy installation.  But I would like more head-room
and increased isolation for both internal assets and client assets.  

I have upgraded from the unnumbered version of weave which has served
me since late 2014, to weave v1.5.1.  My intent at the moment is to use
weave as a docker plugin, though I have tried a number of experiments
from both the proxy route and the plugin route.  So if you see any
cruft which does not belong, please point it out.  

My first task, and the one which has frustrated me for far too long is
to get my NFS server registered to my puppet server, so that the
rebuilding can begin.  My architecture looks like this:

```
bare-metal-machines:
  docker-host-001:
    ip: 10.0.1.51/24
    containers:
      - puppet.example.net:
          ip: 10.0.1.146/24
          ip: 10.0.1.125/24 <-- assigned by ipam
  docker-host-014:
    ip: 10.0.1.64/24
    containers:
      - nfs.example.net
          ip: 10.0.1.25/24
          ip: 10.0.1.111/24 <-- assigned by ipam
```

From d001 I can ping these weave addresses 
10.0.1.51, 10.0.1.64, 10.0.1.125 and 10.0.1.146 but not 10.0.1.25 nor 10.0.1.111.  

Likewise, from d014 I can ping 
10.0.1.51, 10.0.1.64, 10.0.1.25 and 10.0.1.111 but neither 10.0.1.125 and 10.0.1.146.  

Further details including `ip route` output and the contents of scripts
I'm using to drive the orchestration are available here:

	https://gist.github.com/hesco/5f1001cc665f1d76a4fac19b9885b51b

Can anyone please offer some guidance here, pointers to relevant
documentation, your opinion of my most humorous line of code?

Thanks,
-- Hugh Esco 

-- 
Hugh Esco <hesco@yourmessagedelivered.com>

**Comment by bboreham** [comment] 2016-05-31 09:48
Brief initial answers; it will take a bit longer to analyze your example.

> Is it possible for the weave-dns server to manage a zone file other than weave.local.?

Yes, see https://www.weave.works/docs/net/latest/weavedns/managing-domains-weavedns/#local-domain

> How do I prevent IPAM from creating an address when to preserve legacy behavior I need to make assignments?

You tell IPAM to work within a range smaller than the subnet - https://www.weave.works/docs/net/latest/ipam/allocation-multi-ipam/#manual

**Comment by bboreham** [comment] 2016-06-02 13:21
This output:

````
root@nfs:~# ip route                                                                                                                                                     
default via 172.18.0.1 dev eth1 
10.0.1.0/24 dev ethwe0  proto kernel  scope link  src 10.0.1.111 
10.0.1.0/24 dev ethwe  proto kernel  scope link  src 10.0.1.25 
````

suggests you connected this container via the plugin as well as either the proxy or `weave attach` - the former produces `ethwe0` and the latter `ethwe`.

I cannot say how this would directly lead to the symptoms you reported, but it's not really what you'd want so best to cure this and then see how it looks.

Right now, I can't actually see where in the files you supplied this happens.

Related: #1988

**Comment by rade** [comment] 2016-06-20 03:04
I am closing this since we cannot reproduce it; please re-open if steps to reproduce become available.

**Closed by rade** 2016-06-20 03:04 UTC
