### ISSUE TITLE
Peers connect failed since host clock skew exceeds 900s limit

### ISSUE THREAD

**Issue by jacknlliu** [weaveworks/weave#3053] opened 2017-07-10 02:26 UTC
Peers connect failed, the following output show the error.
```
$ weave status connections
-> 192.168.1.101:6783    failed      host clock skew of 33166s exceeds 900s limit, retry: 2017-07-09 16:59:26.882288888 +0000 UTC 
```

## What happened?
Two hosts use weave to connect the docker containers.

On host A,
```
$ weave launch 192.168.1.200
```

On host B,
```
$ weave launch 192.168.1.101
```

and show the status
```
$ weave status
```
Then we get failed.
```
Version: git-d8222d76d957 (up to date; next check at 0001/01/01 00:00:00)

        Service: router
       Protocol: weave 1..2
           Name: 62:3a:88:f1:51:6e(arm)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 1
    Connections: 1 (1 failed)
          Peers: 1
 TrustedSubnets: none
```

```
$ weave version
2.0.1

$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:22:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:51 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux  4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bboreham** [comment] 2017-07-10 13:35
Can you check if the two hosts have the same time?

**Comment by marccarre** [comment] 2017-07-10 15:50
Some background on this error: the clock skew could be problematic for the _gossip_ protocol Weave Net uses under the cover to exchange data between the various peers making your cluster. See also [here](https://github.com/weaveworks/weave/blob/master/nameserver/nameserver.go#L24) and [here](https://github.com/weaveworks/weave/blob/master/nameserver/nameserver.go#L211).

**If** the two hosts have a different time (as asked by **@bboreham** above), then you may want to synchronise these [using NTP](https://askubuntu.com/questions/254826/how-to-force-a-clock-update-using-ntp).

**Comment by jacknlliu** [comment] 2017-07-10 16:20
@bboreham  @marccarre  the two hosts don't have the same time, but I wonder if it will work with this issue. I test [etcd](http://docker-k8s-lab.readthedocs.io/en/latest/docker/docker-etcd.html), and it will work with this issue even though some warning print.

**Comment by marccarre** [comment] 2017-07-10 16:52
[Some people claimed etcd is resilient to skews](https://groups.google.com/forum/#!msg/etcd-dev/jc46d6xmWTs/61AqjPVsAwAJ), so yes, it could be that you will not experience issues on this specific front, however, in general, 
- it is a bad idea to run distributed systems across machines having a large skew, as many systems and algorithms rely on timestamps for ordering, consensus, TTLs, etc.
- some systems will explicitly rely on you to run `ntp` on the various hosts forming the cluster, e.g. [Kubernetes](https://github.com/kubernetes/kubernetes/issues/6159#issuecomment-252396106) or [Cassandra](https://stackoverflow.com/questions/34898693/why-cassandra-cluster-need-synchronized-clocks-between-nodes),

so, IMHO, it definitely would be safer and preferable to synchronise these clocks, @jacknlliu.
Is this something you have control over?

---- 
@bboreham, do you reckon [this](https://github.com/coreos/etcd/blob/master/pkg/monotime/nanotime.go) could be useful?

**Comment by jacknlliu** [comment] 2017-07-11 00:36
@marccarre  thank you very much for sharing your brilliant opinion.

**Comment by bboreham** [comment] 2017-07-11 11:45
We use the time to remove "tombstones" which replace deleted DNS entries from the eventually-consistent data structure. 

If two clocks are very out of sync then WeaveDNS would delete current data. 

Without a mechanism to remove tombstone entries the data structure will grow bigger and bigger and consume more machine resources over time. 

Etcd is completely different: it is a full-consensus system that will freeze under a network partition. Different trade-offs.

**Comment by bboreham** [comment] 2017-07-18 01:06
Closing because this is working as designed.

**Closed by bboreham** 2017-07-18 01:06 UTC
Labels: question, state/need-more-info, [component/dns]
