### ISSUE TITLE
'weave run' fails with 'container X not running'

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2492] opened 2016-08-26 19:54 UTC
Following the [CoreOS guide](https://github.com/weaveworks/guides/tree/master/coreos-simple), I ran

```
$ weave run 10.0.1.1/24 -t -i weaveworks/weave-gs-simple-hw
Unable to find image 'weaveworks/weave-gs-simple-hw:latest' locally
latest: Pulling from weaveworks/weave-gs-simple-hw
a3ed95caeb02: Already exists
76a4cab4eb20: Pulling fs layer
d2ff49536f4d: Pulling fs layer
b811fda04228: Pulling fs layer
a3ed95caeb02: Pulling fs layer
001059a90636: Pulling fs layer
028a06c2f568: Pulling fs layer
301912611368: Pulling fs layer
983d3447d2c9: Pulling fs layer
b362f35e83bb: Pulling fs layer
26a5c45a93aa: Pulling fs layer
5d3aac773536: Pulling fs layer
a3ed95caeb02: Waiting
001059a90636: Waiting
028a06c2f568: Waiting
301912611368: Waiting
983d3447d2c9: Waiting
b362f35e83bb: Waiting
26a5c45a93aa: Waiting
5d3aac773536: Waiting
d2ff49536f4d: Verifying Checksum
d2ff49536f4d: Download complete
b811fda04228: Verifying Checksum
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
028a06c2f568: Verifying Checksum
028a06c2f568: Download complete
001059a90636: Verifying Checksum
001059a90636: Download complete
301912611368: Verifying Checksum
301912611368: Download complete
983d3447d2c9: Verifying Checksum
983d3447d2c9: Download complete
b362f35e83bb: Download complete
26a5c45a93aa: Verifying Checksum
26a5c45a93aa: Download complete
5d3aac773536: Verifying Checksum
5d3aac773536: Download complete
76a4cab4eb20: Verifying Checksum
76a4cab4eb20: Download complete
76a4cab4eb20: Pull complete
d2ff49536f4d: Pull complete
b811fda04228: Pull complete
a3ed95caeb02: Pull complete
001059a90636: Pull complete
028a06c2f568: Pull complete
301912611368: Pull complete
983d3447d2c9: Pull complete
b362f35e83bb: Pull complete
26a5c45a93aa: Pull complete
5d3aac773536: Pull complete
Digest: sha256:9927112d5b04a6d0c75f27073f6ae179fde69e1118e2169bba3b4690abb02ca3
Status: Downloaded newer image for weaveworks/weave-gs-simple-hw:latest
container a7857e0c09c9514657c40ee893fce10f13f0a58d3bf63263e3106d7b1d7b5f55 not running
```

The container did apparently start and exit...

```
$ docker inspect -f '{{json .State}}' a7857e0c09c951 | jq 
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2016-08-26T19:43:36.640230435Z",
  "FinishedAt": "2016-08-26T19:43:36.711107279Z"
}
```

Repeating the command a few more times does eventually make it succeed...

```
$ weave run 10.0.1.1/24 -t -i weaveworks/weave-gs-simple-hw
container 60a916e1b4185c04f33255fb0b06d82fc7b9b0aad3a9541074d58a0a34600e52 not running
$ weave run 10.0.1.1/24 -t -i weaveworks/weave-gs-simple-hw
container 052b5c78e718b71263b145587c5b3677eaf622f2dc8ddc5e4eabfc9b614fcb6c not running
$ weave run 10.0.1.1/24 -t -i weaveworks/weave-gs-simple-hw
78f0f5e27832f215996bdc4b6935065c79b5993b37f1931a9e744a3e654e6037
$ weave ps
weave:expose d2:e2:3d:cc:92:05
78f0f5e27832 2a:95:7f:92:e8:d1 10.0.1.1/24
```

So it looks like there is some race condition here somewhere.

**Comment by rade** [comment] 2016-08-26 20:03
I wonder whether this is a bug in the particular image, given that the weave tests make heavy use of 'weave run', so any general problems with that should have cropped up earlier. Perhaps the container is exploding when the contained app starts prior to weave networking having been fully configured? @errordeveloper any clues? Where is that image produced?

**Comment by marccarre** [comment] 2016-11-02 17:04
@rade, I have just tried to reproduce it on my machine, but this unfortunately worked first time.
I followed the steps from the guide, which eventually pulled Weave Net `1.7.2` on both VMs, and `weave-gs-simple-hw` under `weave-gs-01` had the same digest as yours.
Do you happen to:
* remember which version of Weave Net you were using?
* have more details on the state of your host and/or VMs at the time? (e.g. output of `dmesg`)

@errordeveloper, have you looked further into this or discussed it with @rade since this was raised late August?

**Comment by rade** [comment] 2016-11-02 17:11
> remember which version of Weave Net you were using?

Whatever was current when I filed the issue, I suspect.

Ditto for docker.

>  more details on the state of your host and/or VMs at the time? (e.g. output of `dmesg`)

from >2 months ago?!? no.

This issue isn't worth spending much time on. If it cannot be reproduced easily, close as worksforme.

**Comment by marccarre** [comment] 2016-11-02 17:14
> from >2 months ago?!? no.

As I suspected, but was still worth asking I guess.
I will close it for now then. We can always re-open it and gather more details if it happens again.

**Closed by marccarre** 2016-11-02 17:14 UTC
Labels: bug
