### ISSUE TITLE
weave 1.2.0 Containers fail to start

### ISSUE THREAD

**Issue by webts** [weaveworks/weave#1587] opened 2015-10-24 03:17 UTC
since 1.2.0 release my custom containers fail to start. I get the following error 
Post http:///var/run/weave.sock/v1.19/images/create?fromImage=mongo%3Amultihost: dial unix /var/run/weave.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

when I check weave status the socket address is unix:///var/run/weave/weave.sock. in above error it is looking for unix /var/run/weave.sock

reverting back to 1.1.2 all works fine

**Comment by bboreham** [comment] 2015-10-24 05:48
Could you post the command(s) that result in this error, please?

We did move the socket to fix a bug, so whatever environment has the old location stored would have to be re-configured.

**Comment by webts** [comment] 2015-10-26 02:56
this is my weave install unit 
```
    - name: install-weave.service
      command: start
      enable: true
      content: |
        [Unit]
        After=network-online.target
        After=docker.service
        Description=Install Weave
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/bin/mkdir -p /opt/bin/
        ExecStartPre=/usr/bin/curl \
          --silent \
          --location \
          https://github.com/weaveworks/weave/releases/download/latest_release/weave \
          --output /opt/bin/weave
        ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
        ExecStartPre=/usr/bin/docker pull weaveworks/weave:latest
        ExecStartPre=/usr/bin/docker pull weaveworks/weavedns:latest
        ExecStartPre=/usr/bin/docker pull weaveworks/weaveexec:latest
        ExecStart=/bin/echo Weave Installed
```

**Comment by tomwilkie** [comment] 2015-10-27 10:11
Instead of `/usr/bin/docker pull weaveworks/weave:latest`, please use `/opt/bin/weave setup` to ensure you pull the correct version of the images.

I would also note none of the above commands actually seem to start weave, unless I'm missing something.

What command fails with the originally reported error?  And where so you see that error?  It looks like you have the DOCKER_HOST in you environment set to unix:///var/run/weave.sock, whereas it should be set by invoking `eval $(weave env)`.

**Comment by rade** [comment] 2015-11-03 00:24
I am closing this since we cannot reproduce the problem. @webts if you have further info then please re-open.

**Closed by rade** 2015-11-03 00:24 UTC
