### ISSUE TITLE
weave launch not functioning on the latest docker for mac

### ISSUE THREAD

**Issue by the-destro** [weaveworks/weave#2391] opened 2016-06-21 20:34 UTC
The latest beta is throwing an error on weave launch:
`unable to create network: API error (500): invalid ipam driver: "weavemesh"`

**Comment by errordeveloper** [comment] 2016-06-21 22:50
Just for the record, are we talking about `1.12.0-rc2-beta16`?

**Comment by errordeveloper** [comment] 2016-06-21 22:59
I can confirm this is the case on Docker for Mac version `1.12.0-rc2-beta16`. @rade have we tested Docker plugin on `1.12.0-rc2` in general? Docker for Mac ships vanilla builds, as far as I am aware.

**Comment by errordeveloper** [comment] 2016-06-21 22:59
@the-destro is this in connection with https://github.com/kubernetes/kubernetes-anywhere/issues/138 that you have reported earlier?

**Comment by rade** [comment] 2016-06-22 01:39
> have we tested Docker plugin on 1.12.0-rc2 in general?

We've run our entire test suite against 1.12.0-rc1, iirc.

**Comment by errordeveloper** [comment] 2016-06-22 17:04
One thing I just realised is that I was testing this using Weave Net 1.5.2. Having tested with latest 1.6.0, I can confirm that this issue only occurs on Docker for Mac 1.12.0-rc2-beta16 and with Weave Net 1.5.2. I doesn't occur with Weave 1.5.2 on Boot2Docker 1.12.0-rc2. All works well with Docker for Mac and Weave Net 1.6.0.

**Comment by errordeveloper** [comment] 2016-06-22 17:04
@the-destro please upgrade to Weave Net 1.6.0.

**Comment by mongrelion** [comment] 2016-06-24 08:44
I'm having the same issue running on Linux (Centos 7):
```
$ weave launch
unable to create network: API error (500): invalid ipam driver: "weavemesh"

$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
1d06ff78f8de        weaveworks/plugin:1.6.0      "/home/weave/plugin"     11 seconds ago      Up 8 seconds                            weaveplugin
5bc96b29e3eb        weaveworks/weaveexec:1.6.0   "/home/weave/weavepro"   12 seconds ago      Up 10 seconds                           weaveproxy
adb78fc332cc        weaveworks/weave:1.6.0       "/home/weave/weaver -"   13 seconds ago      Up 12 seconds                           weave
$ weave version
weave script 1.6.0
weave router 1.6.0
weave proxy  1.6.0
weave plugin 1.6.0
$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
$ uname -a
Linux localhost.localdomain 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by errordeveloper** [comment] 2016-06-24 10:38
I wonder what may be in common between Moby (the Alpine derivative used in
Docker for Mac) and CentOS?

**Comment by errordeveloper** [comment] 2016-06-24 11:33
@mongrelion currently I'm not able to reproduce this with either versions (1.5.2 and 1.6.0). Can you reproduce it consistently?

**Comment by errordeveloper** [comment] 2016-06-24 11:43
@mongrelion if you can reproduce it, please use `weave launch --log-level=debug` and provide the output of `docker logs weaveplugin`.

**Comment by mongrelion** [comment] 2016-06-24 11:46
@errordeveloper sorry, I can't seem to reproduce it anymore. I'm currently trying it all out in a Vagrant machine which I created last night and ran into that issue.
I just recreated the machine (Docker & Weave installation steps are automated) and can't seem to reproduce the error anymore. I'm running into other issues but those are off topic for this thread.
Sorry about the fuzz.

**Comment by errordeveloper** [comment] 2016-06-24 11:52
@mongrelion ok, so I am suspecting it could be a race condition in Docker plugins API. Could you share the Vagrantfile, and I'll try to run it in a loop for a while?

**Comment by mongrelion** [comment] 2016-06-24 11:55
@errordeveloper [here](https://github.com/weaveworks/weaveDemo/tree/9320455258202848cef91244b7628d6a97e5f4a0/examples/swarmkit) you go.
**Heads up**: you'll need Ansible installed. Ping me on Slack if you need help with that.

**Comment by errordeveloper** [comment] 2016-06-24 16:03
I ran the following in that directory:
```
while true; do (make destroy ; make up) && vagrant ssh -c "weave launch && weave status" ; [ "$?" -ne 0 ] && break || continue ; do
```
The error didn't come up in 26 iterations.

**Comment by rade** [comment] 2016-06-27 13:25
I am seeing this error after `docker swarm init`. See #2403.

@the-destro @mongrelion did you perhaps run `docker swarm init`? What does `docker network ls` return?

**Comment by the-destro** [comment] 2016-06-27 23:07
@rade yes I did. I have tried after leaving the swarm as well and got the same error. 
```$ weave launch --log-level=debug
unable to create network: API error (500): invalid ipam driver: "weavemesh" ```
```NETWORK ID          NAME                DRIVER              SCOPE
50c83b482c45        bridge              bridge              local
c9991d2ca8c4        docker_gwbridge     bridge              local
bbf39d6c4934        host                host                local
32g4baxfxlyi        ingress             overlay             swarm
22ed0bfac9cf        isolated_nw         bridge              local
28d734abc0f8        none                null                local```

```
$ docker logs weaveplugin
INFO: 2016/06/27 23:05:36.615258 Weave plugin 1.6.0 Command line options: [--log-level=debug]
INFO: 2016/06/27 23:05:36.617946 Docker API on unix:///var/run/docker.sock: &[Os=linux KernelVersion=4.4.13-moby BuildTime=2016-06-17T22:09:20.440355664+00:00 ApiVersion=1.24 GitCommit=a7119de GoVersion=go1.6.2 Version=1.12.0-rc2 Arch=amd64 Experimental=true]
INFO: 2016/06/27 23:05:36.618103 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2016/06/27 23:05:36.618179 Listening on /run/docker/plugins/weavemesh.sock for local scope```

```$ docker images | grep 'weave'
weaveworks/plugin                    1.6.0               af9b3731ed7a        7 days ago          87.06 MB
weaveworks/weaveexec                 1.6.0               0d4dc9773eb8        7 days ago          74.7 MB
weaveworks/weave                     1.6.0               005ff267f724        7 days ago          28.19 MB
weaveworks/weavedb                   latest              9de1af088a49        2 weeks ago         244 B
weaveworks/kubernetes-anywhere       toolbox             572c95debbdb        6 weeks ago         448 MB
weaveworks/kubernetes-anywhere       toolbox-v1.2        572c95debbdb        6 weeks ago         448 MB
weaveworks/kubernetes-anywhere       toolbox-v1.2.4      572c95debbdb        6 weeks ago         448 MB```

**Comment by rade** [comment] 2016-06-28 01:34
> yes I did.

I which case the problem you are seeing is very likely the same as #2403.

>  I have tried after leaving the swarm as well and got the same error. 

See https://github.com/weaveworks/weave/issues/2403#issuecomment-228746464

@mongrelion were you too running `docker swarm init`?

**Comment by mongrelion** [comment] 2016-06-28 07:38
@rade I think I might have, yes, as I was doing tests to integrate the [demo app](https://github.com/weaveworks/weaveDemo) with SwarmKit and ran into that error at some point.

**Comment by rade** [comment] 2016-06-28 07:40
Thanks for the confirmation. I am going to close this as a dup of #2403 then.

**Closed by rade** 2016-06-28 07:40 UTC
Labels: bug
