### ISSUE TITLE
Launching plugin hangs

### ISSUE THREAD

**Issue by grkvlt** [weaveworks/weave#2458] opened 2016-07-31 02:00 UTC
When I run `weave launch-plugin` the process gets as far as creating the required containers and starting them, but then hangs. On inspecting the process list, it seems that it is waiting for `weaveutil create-plugin-network weave weavemesh` to finish. If I run`docker network create --driver weavemesh weave` manually, this seems to work, and the launcher task completes. I am using Weave 1.6.0 on CentOS 7.2 with a 3.10 kernel and Docker 1.11.2 with TLS enabled, and appropriately configured with environment variables, which are being passed to weave using `sudo -E`.

**Comment by bboreham** [comment] 2016-07-31 07:34
Can you supply the output of `docker logs weaveplugin` please, at the point where it hangs?

If nothing interesting there, the logs from the Docker daemon may give a clue.

Also it would be helpful to get a transcript of all the steps you took to launch the different parts of weave.

**Comment by timcharper** [comment] 2016-08-10 16:29
I'm seeing this as well; the `docker logs weaveplugin` is outputting a TON of logs, 275000+ lines in a matter of minutes.

Here's a sampling:

```
INFO: 2016/08/10 16:26:00.314045 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.314216 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.314224 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.314389 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.314527 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.314721 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.314752 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.314872 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315048 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315163 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.315177 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315342 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315509 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315599 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.315666 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.315809 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316039 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316063 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.316178 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316335 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316502 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316525 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.316661 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316797 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.316952 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.316962 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317088 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317220 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317345 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317433 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.317469 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317627 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317780 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.317933 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.317945 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318077 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318283 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318451 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.318469 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318655 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318856 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.318960 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.319052 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319229 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319402 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319477 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.319612 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319790 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319972 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.319975 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.320113 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.320296 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.320439 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.320492 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.320600 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.320770 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.320971 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.321408 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.321876 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.321947 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.322101 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.322402 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.322569 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.322787 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.322953 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.323027 [ipam] RequestPool weavelocal   map[]
INFO: 2016/08/10 16:26:00.323095 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
INFO: 2016/08/10 16:26:00.323415 [ipam] ReleasePool weave-10.32.0.0/12-10.32.0.0/12
```

**Comment by rade** [comment] 2016-08-10 16:32
@bboreham is this essentially the same underlying problem as #2469?

**Comment by timcharper** [comment] 2016-08-10 16:37
It looks like I might have had dangling docker containers from a previous rather forceful shutdown of docker, and the processes were contending over the resources.

**Comment by timcharper** [comment] 2016-08-10 16:38
@rade , No, I don't think so. But I'll investigate and see if I can reproduce that one.

**Comment by timcharper** [comment] 2016-08-10 16:43
Oh, @rade what I was experiencing was not when trying to create a new cluster; I only want one weave cluster.

**Comment by bboreham** [comment] 2016-08-10 16:51
Those logs do indeed look very like #2469; @timcharper were you (a) running Docker 1.12 and (b) had previously run `weave expose` ?

**Comment by timcharper** [comment] 2016-08-10 19:08
@bboreham yes!

**Comment by timcharper** [comment] 2016-08-10 19:08
We are able to resolve it by at least manually deleting all of the weave related interfaces, and removing all of the weave containers, and starting again.

**Comment by timcharper** [comment] 2016-08-10 19:09
We can cause it to happen again by stopping docker, and running `rm -rf /var/lib/docker/*`, then restarting docker and trying to run weave again.

**Comment by bboreham** [comment] 2016-08-12 14:48
OK, so I believe @timcharper your issue is the same as #2469 but not the same as the original issue here.

@grkvlt could you supply more information about your symptoms?

**Comment by Bregor** [comment] 2016-09-27 15:08
Looks like same here.

Weave-1.7.0

    ...
    INFO: 2016/09/27 15:05:05.808723 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    INFO: 2016/09/27 15:05:05.808960 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    INFO: 2016/09/27 15:05:05.809065 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    INFO: 2016/09/27 15:05:05.809288 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    INFO: 2016/09/27 15:05:05.809398 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    INFO: 2016/09/27 15:05:05.809503 [ipam] ReleasePool weave-192.168.0.0/16-192.168.0.0/16
    ...

Thousands of them. 

Docker daemon eats >100% CPU all the time.

You can see `docker info` and traces with and without weave here: https://gist.github.com/Bregor/5322971294c5acb58acb6809a4ea4a05

`docker info`: https://gist.github.com/Bregor/5322971294c5acb58acb6809a4ea4a05#file-info
Daemon trace with weave: https://gist.github.com/Bregor/5322971294c5acb58acb6809a4ea4a05#file-trace
Daemon trace without weave: https://gist.github.com/Bregor/5322971294c5acb58acb6809a4ea4a05#file-no-weave-trace

**Comment by bboreham** [comment] 2016-09-28 17:09
Having discussed with @bregor further on Slack, we were unable to figure out how it got into that state.

Closing due to lack of information on the original issue.

**Closed by bboreham** 2016-09-28 17:09 UTC
Labels: bug, [component/plugin]
