### ISSUE TITLE
Weave loses connection to self and peers on restart

### ISSUE THREAD

**Issue by gondor** [weaveworks/weave#2298] opened 2016-05-15 17:50 UTC
We've been testing for failure and during a "host" restart, Weave will load within Docker as expected however issuing a ```weave status``` shows a connection refused.

The current workaround is to:
- ```weave stop```
- ```weave launch-router ...```
- ```weave launch-plugin```

What is the approach in case of a host/machine restart? 

**Weave - Before Restart**

```
root@slave1 etc]# weave status

        Version: 1.5.1 (up to date; next check at 2016/05/15 23:52:07)

        Service: router
       Protocol: weave 1..2
           Name: 52:d0:1d:bd:51:56(slave1)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 1
    Connections: 1 (1 established)
          Peers: 2 (with 2 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: idle
          Range: 10.2.0.0-10.2.255.255
  DefaultSubnet: 10.2.1.0/24

        Service: dns
         Domain: weave.local.
       Upstream: 10.0.2.3
            TTL: 1
        Entries: 0

        Service: plugin
     DriverName: weave
```

**Weave - After Restart -- issuing "weave status"**

```
curl: (7) Failed to connect to 127.0.0.1 port 6784: Connection refused

        Service: plugin
     DriverName: weave
```

**docker ps**

```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
5c75258f4450        weaveworks/plugin:1.5.1   "/home/weave/plugin"     6 minutes ago       Up 48 seconds                           weaveplugin
97ea929fc947        weaveworks/weave:1.5.1    "/home/weave/weaver -"   6 minutes ago       Up 48 seconds                           weave
```

**Comment by bboreham** [comment] 2016-05-16 13:28
It looks like you are choosing to run the Weave router and plugin, but not the proxy.

The proxy is required for automatic restarts to work, as noted at https://www.weave.works/docs/net/latest/troubleshooting/#reboots

Closing as duplicate of #2112

**Closed by bboreham** 2016-05-16 13:28 UTC
