### ISSUE TITLE
NO_MASQ_LOCAL=1 is not working with weave 2.5.2- Not able to get source client IP. It showing weave subnet

### ISSUE THREAD

**Issue by Srivalle** [weaveworks/weave#3709] opened 2019-10-10 07:52 UTC
I am using K8 version 1.15.4 and weave net version 2.5.2 . 
I want perserve source client IP. As per the document i enabled NO_MASQ_LOCAL=1 in weavenet.yaml file . But i am getting the source client IP instead i am getting weavenet subnet Ip . How to preserve source client IP in weavenet 2.5.2

**Comment by bboreham** [comment] 2019-10-10 08:56
Which document?

**Comment by bboreham** [comment] 2019-10-10 08:58
It's much harder to help when you decide not to fill in the information requested.
Like "## How to reproduce it? "

**Comment by Srivalle** [comment] 2019-11-20 16:38
Hi , I also face the same issue . 

I am have kubernetes 1.15.4 version  and weavenet 2.5.2. 

I set NO_MASQ_LOCAL to 1  But still i am not getting source IP  . It is showing only weave subnet IP. How to get source IP in k8 platform with weavenet 2.5.2

**Comment by Srivalle** [comment] 2019-11-20 16:39
https://www.weave.works/docs/net/latest/kubernetes/kube-addon/

it says if we give NO_MASQ_LOCAL to 1 , we can preserve Source IP.

**Comment by murali-reddy** [comment] 2019-11-21 07:51
@Srivalle Please fill in the details as requested.

**Comment by SeMeKh** [comment] 2020-02-16 11:20
@Srivalle Have you set `service.spec.externalTrafficPolicy= Local` on the service? IIRC, if you don't, you'll get kube-proxy's IP as source.
See: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

**Comment by vipinjn24** [comment] 2020-12-17 14:23
I am having the same issue with the my single node kubeadm installation.

Weave + Metallb (Layer2 configuration) + Traefik (But using other pods service directly is also not showing client IP).

Then I removed Weave and deployed Calico and it all works as smooth for all required services.

**Comment by maxisam** [comment] 2021-01-28 18:02
I am using 2.8.0. It doesn't preserve the ip with externalTrafficPolicy = "Local"

**Comment by bboreham** [comment] 2021-01-29 14:24
This is tested on every commit: https://github.com/weaveworks/weave/blob/ba64f8e8eb1f4ba5cd85189a51a1312de984bade/test/840_weave_kube_3_test.sh#L364-L374

Please note comments above about not providing details.  I'm going to close this because it never went anywhere.

**Closed by bboreham** 2021-01-29 14:24 UTC
