### ISSUE TITLE
Containers attached to weave net do not restart after docker service restart

### ISSUE THREAD

**Issue by avkonst** [weaveworks/weave#3009] opened 2017-06-07 10:09 UTC
I am creating a container with `restart` policy `always` and attached to weave net. The container does not restart after docker engine restart. I think it is a bug.

Here is the reproducer:
```bash
#!/usr/bin/env bash

set -e

weave launch \
        --ipalloc-range 10.32.0.0/13 --ipalloc-default-subnet 10.32.0.0/12 \
        --name=::1 --ipalloc-init seed=::1,::2,::3,::4

docker run --name sleep-client -h sleep-client.weave.local -dti \
        --init \
        --net=weave --ip=10.40.1.11 \
        $(weave dns-args) \
        --restart always \
        ubuntu:16.04 \
        sleep 2000

docker ps

sleep 5

service docker restart

sleep 5

docker ps

```
Here is the output:

```bash
vagrant@clusterlite-build:~$ sudo /vagrant/reproducer.sh
ecc737bd9ee65077a98010a5730ff74d5c0af490804b687f71d85ee9386aca67
CONTAINER ID        IMAGE                        COMMAND                  CREATED                  STATUS                  PORTS               NAMES
ecc737bd9ee6        ubuntu:16.04                 "sleep 2000"             Less than a second ago   Up Less than a second                       sleep-client
afb03a4796d3        weaveworks/plugin:1.9.7      "/home/weave/plugin"     2 seconds ago            Up 1 second                                 weaveplugin
04ba203c726a        weaveworks/weaveexec:1.9.7   "/home/weave/weave..."   2 seconds ago            Up 2 seconds                                weaveproxy
d50b04b596fc        weaveworks/weave:1.9.7       "/home/weave/weave..."   4 seconds ago            Up 3 seconds                                weave
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS               NAMES
afb03a4796d3        weaveworks/plugin:1.9.7      "/home/weave/plugin"     About a minute ago   Up 20 seconds                           weaveplugin
04ba203c726a        weaveworks/weaveexec:1.9.7   "/home/weave/weave..."   About a minute ago   Up 20 seconds                           weaveproxy
d50b04b596fc        weaveworks/weave:1.9.7       "/home/weave/weave..."   About a minute ago   Up 20 seconds                           weave
```

## What you expected to happen?
I expect sleep-client container to be in the list both times.

## What happened?
It is in the list before docker restart and it is not in the list after docker restart.

## How to reproduce it?
see the script above

## Anything else we need to know?
environment: vagrant, virtualbox, ubuntu 16:04
weave 1.9.5 and 1.9.7
docker 1.13.1

## Logs:
I will attach docker and weave service logs

**Comment by avkonst** [comment] 2017-06-07 10:12
Logs attached
[logs.zip](https://github.com/weaveworks/weave/files/1057661/logs.zip)

**Comment by marccarre** [comment] 2017-06-08 10:25
@avkonst, I was able to reproduce the issue, it is essentially that the plugin hasn't started yet when Docker tries to restart your container, see:
```
level=error msg="Failed to start container <cid>: legacy plugin: plugin not found"
```
However, this is a known limitation of Docker plugins (see #2222). Alternatives are to either:
1. use [Weave Net as a Docker proxy](https://www.weave.works/docs/net/latest/weave-docker-api/), or
2. use [our release candidate](https://store.docker.com/plugins/weave-net-plugin/plans/bc0362d7-a1fe-4af9-9555-49c9445f9a38?tab=instructions) of Weave Net [V2 plugin](https://docs.docker.com/engine/extend/config/).

I am closing this issue as this seems to be a duplicate of #2222, but feel free to reopen if you believe this is a different issue or if you have any other question.

**Closed by marccarre** 2017-06-08 10:25 UTC

**Comment by marccarre** [comment] 2017-06-08 10:32
For the record, details on the reproduction of the issue:
- Steps:
```
$ weave launch
$ docker run --name c1 -h c1.weave.local --net=weave $(weave dns-args) -d --restart always alpine tail -f /dev/null
d961230715d39d3ce0b128ed0c380023137f1ec6c3a12f5d42be81ede395f659
$ docker ps
$ systemctl restart docker
$ docker ps
```
- Docker tries to restart the container...
```
time="2017-06-08T10:17:59.154018943Z" level=error msg="Failed to start container d961230715d39d3ce0b128ed0c380023137f1ec6c3a12f5d42be81ede395f659: legacy plugin: plugin not found"
```
- but Weave Net hasn't been started just yet, see timestamps:
```
INFO: 2017/06/08 10:17:59.201801 Weave plugin 1.9.7 Command line options: []
INFO: 2017/06/08 10:17:59.202445 Docker API on unix:///var/run/docker.sock: &[Version=1.13.1 GitCommit=092cba3 GoVersion=go1.7.5 Arch=amd64 BuildTime=2017-02-08T06:50:14.717554785+00:00 ApiVersion=1.26 MinAPIVersion=1.12 Os=linux KernelVersion=4.8.0-45-generic]
INFO: 2017/06/08 10:17:59.202526 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2017/06/08 10:17:59.202560 Listening on /run/docker/plugins/weavemesh.sock for local scope
```

**Comment by avkonst** [comment] 2017-06-08 10:40
Thanks. I use weave launch script to install. How can I try the release
candidate?

**Comment by marccarre** [comment] 2017-06-08 10:45
Welcome!
The V2 plugin is quite different so you wouldn't start it with `weave launch`.
I have linked the instructions to set it up [here](https://github.com/weaveworks/weave/issues/3009#issuecomment-307063829): 
> 2. use [our release candidate](https://store.docker.com/plugins/weave-net-plugin/plans/bc0362d7-a1fe-4af9-9555-49c9445f9a38?tab=instructions)

**Comment by avkonst** [comment] 2017-06-08 10:49
These instructions assume it is with docker swarm. But I do not use swarm
feature. Can it be used without swarm?

**Comment by marccarre** [comment] 2017-06-08 11:10
Then this leaves you: 
> 1. use [Weave Net as a Docker proxy](https://www.weave.works/docs/net/latest/weave-docker-api/)

**Comment by avkonst** [comment] 2017-06-08 11:18
Thanks. I understand that proxy is what going to be replaced by the plugin
in the futufe? What is weave's long term roadmap in relation to support of
the weave script as a standalone tool? I mean are you planning to retire it
encouraging people to use weave only as a plugin for kubernetes and swarm?
Or you have got plans to support weave as standalone SDN solution requiring
only pure 'docker run'?

**Comment by marccarre** [comment] 2017-06-08 11:30
@avkonst, no, we do not plan to replace the proxy with anything else, you will still have all of the below supported if you want to set up Weave Net:
1. Docker plugin (`weave launch` & `eval $(weave env)`)
2. Docker plugin (`weave launch` & `docker run --net=weave $(weave dns-args)`)
3. [Docker V2 plugin via Docker Swarm](https://store.docker.com/plugins/weave-net-plugin/plans/bc0362d7-a1fe-4af9-9555-49c9445f9a38?tab=instructions)
4. [Kubernetes addon](https://www.weave.works/docs/net/latest/kube-addon/) a.k.a. `weave-kube`
5. [CNI plugin](https://www.weave.works/docs/net/latest/cni-plugin/) for Mesos (but also works with Kubernetes)

The Docker V2 plugin is just being added to ease integration with Docker Swarm. 
However, Docker may or may not improve the API for V1 plugins, so I cannot comment on this unfortunately, as I do not have visibility.

**Comment by avkonst** [comment] 2017-06-08 11:34
Is the difference between 1 and 2 that the first uses proxy to attach
containers to the net and the second uses docker plugin integration? Why do
you label the first as 'docker plugin' too?

**Comment by marccarre** [comment] 2017-06-08 11:35
Apologies, clearly a typo (edited the above).

**Comment by avkonst** [comment] 2017-06-08 11:44
Thank you very much. All great! Will try the first option.

**Comment by marccarre** [comment] 2017-06-08 11:50
> Is the difference between 1 and 2 that the first uses proxy to attach
containers to the net and the second uses docker plugin integration?

Correct.

In the case of the proxy, when you run your `docker run` commands, you talk to Weave Net (which exposes an API similar to Docker, hence "proxy") instead of talking to Docker directly. Weave Net then ensures that everything is ready for your container: that the container's namespace is properly created, that the creation of the `veth` network interface inside the container happens properly, that the `veth`network interface is ready, that the container has an IP, and only then actually run your container's `ENTRYPOINT`/`CMD`.

In the case of the plugin, it is kind of the other way around, we conform to some API Docker exposes in order to hook Weave Net. However, as a result, we do not have as much control over the full lifecycle as we would for the proxy.

> Thank you very much. All great! Will try the first option.

Welcome! Let us know how it goes! 👍

**Comment by avkonst** [comment] 2017-06-08 12:05
I appreciate if you answer few more questions on weave architecture. I see the containers / images deployed by weave are: plugin, weave, weaveexec, weavedb. 

1. I understand the 'plugin' container is what being used in the option 2 from your list. If I switch to proxy (option 1 from your list), do I need this container running?
2. What is the role of weave container? is it where the actual router logic lives, which manages fast path routes and packet encapsulation in case of pcap mode?
3. weaveexec is pulled and runs as weaveproxy. Is it the container where this recommended proxy-based functionality is deployed?
4. I do not see weavedb image running.. when is it used? what will get broken if I delete it? I had the impression it delivers the volume to store IPAM managed IP assignments. Is that right? If I do not use automated IP address assignment, may I safely delete it?

Thanks in advance for your answer and great SDN solution!

**Comment by bboreham** [comment] 2017-06-08 12:39
1. no (but in the next major release of Weave Net all three containers will turn into one)
2. yes, also IP Address Management and the DNS service.  The weave routers on each node gossip to each other to update their shared view of this data, and network topology.
3. yes
4. it is used as a [data volume container](https://docs.docker.com/engine/tutorials/dockervolumes/) to persist IP Address Management data.  If you delete it, the next time you run the `weave` script it will be recreated.

**Comment by avkonst** [comment] 2017-06-08 12:46
Thank you very much. Very helpful.

**Comment by avkonst** [comment] 2017-06-09 18:14
Thanks guys! Weave proxy alternative works.

**Comment by marccarre** [comment] 2017-06-10 09:31
Excellent! Thanks for the heads up @avkonst!

**Comment by lubars** [comment] 2018-07-15 21:48
@marccarre: we've been using option 2 successfully for some time now, but are switching to option 1 because of the startup order/weavemesh issue (can't use option 3 because we're not using Docker Swarm).

Because  we're running everything remotely (via `docker --host=tcp://<ip address>:2376`), I assume doing an `eval $(weave env)` in the local environment has no effect; instead, we're putting the DOCKER_HOST in /etc/environment, ~/.profile, and ~/.bashrc on the remote machine running dockerd.

However, upon removing the --net=weave (to enable the proxy), containers are no longer seeing each other's hostnames (in the .weave.local domain).  When using the proxy, should these names be resolving, or is some additional step required?  I'm not sure if it makes a difference, but because the list of peers is know to us ahead of time, we have always them as arguments to `weave launch` (as opposed to `weave attach`).

Thanks for any help you can provide.
