### ISSUE TITLE
weave performance slow

### ISSUE THREAD

**Issue by gvenka008c** [weaveworks/weave#2634] opened 2016-11-09 20:31 UTC
We are running CentOS 3.10.0-327.28.2.el7.x86_64. We disabled Encryption and Opened UDP port 6784. We didn't specify any default value for WEAVE_MTU. When we restart weave, it shows fastdatapath but immediately switches to sleeve mode. Thoughts?

# weave version
weave script 1.7.2
weave router 1.7.2
weave proxy  1.7.2
weave plugin 1.7.2

**Comment by bboreham** [comment] 2016-11-09 20:56
What this means is it attempted to set up a fastdp connection but failed back to sleeve. If you look in the logs (`docker logs weave`) you will see it doing this, and maybe some more information about what went wrong.

**Comment by gvenka008c** [comment] 2016-11-09 21:23
Here is the logs

```
INFO: 2016/11/09 14:30:25.978056 EMSGSIZE on send, expecting PMTU update (IP packet was 60028 bytes, payload was 60020 bytes)
INFO: 2016/11/09 14:30:25.978308 overlay_switch ->[56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)] using sleeve
INFO: 2016/11/09 14:30:25.978382 ->[xx.xxx.xx.xx:6783|56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)]: connection fully established
INFO: 2016/11/09 14:30:25.979501 sleeve ->[xx.xxx.xx.xx:6783|56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)]: Effective MTU verified at 1438
INFO: 2016/11/09 14:30:26.062720 Discovered remote MAC 56:4b:3a:ef:b6:c2 at 56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)
INFO: 2016/11/09 14:30:29.487327 Discovered remote MAC 62:df:6c:44:41:e3 at 56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)
INFO: 2016/11/09 14:31:25.474505 overlay_switch ->[56:4b:3a:ef:b6:c2(docker-elements-1.novalocal)] fastdp timed out waiting for vxlan heartbeat

```

**Comment by bboreham** [comment] 2016-11-09 22:08
It just says it timed out; something between the two machines (or at either end) is blocking the VXLAN packets.

**Comment by gvenka008c** [comment] 2016-11-09 22:13
@bboreham Anyway to troubleshoot to see what is blocking VXLAN?

**Comment by bboreham** [comment] 2016-11-09 22:40
You can use a tool like tcpdump or wireshark on port 6784 to see packets being sent at either end.

If the problem is in the middle then it depends on what components lie along the path.  Any firewalls, NAT routers, anything like that?

**Comment by gvenka008c** [comment] 2016-11-10 15:11
@bboreham Bryan, We are running CentOS machine on cloud platform internally using Openstack.

Kernerl Version: 3.10.0-327.36.3.el7.x86_64

**Comment by bboreham** [comment] 2016-12-19 12:12
@gvenka008c did you ever find out what was blocking the VXLAN packets?

**Comment by brb** [comment] 2017-02-23 09:41
I'm closing this.

@gvenka008c If you experience the same problem, please re-open the issue.

**Closed by brb** 2017-02-23 09:41 UTC
Labels: state/investigating

**Comment by SebastienDorgan** [comment] 2017-06-24 20:42
Hello,
I am experiencing the same problem in a similar context except that I run under Ubuntu 16.04 and use docker with an etcd key value store.

**Comment by bboreham** [comment] 2017-06-25 15:36
@SebastienDorgan please open a new issue so we don't confuse the two threads,
post the information requested by the issue template,
and check if something is blocking port 6784 between the two machines.
