### ISSUE TITLE
lxd migrations not working

### ISSUE THREAD

**Issue by sokoow** [weaveworks/weave#2357] opened 2016-06-11 19:29 UTC
I'm moving a lxd container from host to host and are receiving a following message:

[ 5496.041423] weave: received packet on vethwe-bridge with own address as source address
[ 5496.055559] weave: received packet on vethwe-bridge with own address as source address

how to fix that ? networking with the container stops working after moving it around

**Comment by bboreham** [comment] 2016-06-13 09:18
Hi @sokoow, could you give us a transcript of the steps to reproduce this problem?

Also a bit more info on your environment, e.g. OS, version of Weave Net, how you installed it. We only package a version of Weave Net for Docker, which stopped using lxd nearly two years ago.

**Comment by sokoow** [comment] 2016-06-13 16:34
Sure,

So I have two ubuntu 14.04 machines with kernel 4.4.0, they're connected on local network. I'm using the latest Weave Net.

What I'm doing is following:
1. using weave interface as a bridge for lxd
2. on host1 I launch lxd container, it gets an ip address, routes and so on
3. I can ping it from host2 no problem
4. at the moment when I do lxc move container1 host2:container1 , it picks up the IP from dhcp fine, but then loses all the network. MAC addresses are retained over the migration, so I believe that this may be a problem. Suddenly a machine with same mac address appears on completely different host within weave mesh. Something must be cached somewhere. It's all ok when I generate new mac address for the machine.

**Comment by bboreham** [comment] 2016-06-15 13:49
Thanks for the update.  I should note I got confused between `lxc` and `lxd`.

Weave Net does indeed hold a cache of mac->peer, and entries from this cache are expired ten minutes after they are last seen.

I believe, when you have moved the mac address from host1 to host2, Weave is still delivering packets intended for that container to the bridge on host1.  If those packets originated on the bridge on host1, this would result in the message that you saw.

Looking around the Weave Net source, there isn't any provision to update or remove an individual mac address on any basis other than timeout, so this is not a simple thing to fix, sorry.

**Comment by bboreham** [comment] 2016-06-15 14:01
A colleague suggests that the "sleeve" transport may fare better - could you do `weave reset` on all peers then `WEAVE_NO_FASTDP=1 weave launch ...` then try your test again?

**Comment by rade** [comment] 2016-06-20 02:47
@sokoow ping

**Comment by sokoow** [comment] 2016-06-20 16:15
sorry for not replying, I got no time to replicate your suggestions yet, I'll update this issue as soon as I had a moment

**Comment by brb** [comment] 2017-02-23 09:47
I'm closing this issue.

@sokoow please re-open if the issue persists.

**Closed by brb** 2017-02-23 09:47 UTC
Labels: state/investigating
