### ISSUE TITLE
Weave Proxy breaks Docker Exec

### ISSUE THREAD

**Issue by jbrisbin** [weaveworks/weave#2301] opened 2016-05-17 13:57 UTC
I'm writing a Docker client that uses Akka HTTP and accesses the remote REST API to manipulate some Docker containers running the Riak Time Series database. I was having an issue I couldn't track down and finally realized it was because I was using the Weave proxy during the tests. When I run a command that produces multi-line output (with newlines), the proxy somehow gets confused and sends a malformed response back to the client. Somehow there are newlines in an HTTP header name. Not sure how that happens but I suppose it has to do with how the chunked data is being returned from Docker and not supported properly by the proxy.

The project I was seeing the issue with is here: https://github.com/basho-labs/riak-test-docker

Just running the single test with `sbt test` should manifest the issue if `DOCKER_HOST` is set to point to the Weave proxy (e.g. by making sure `weave env` is eval'd into the ENV before running the test).

**Comment by bboreham** [comment] 2016-05-17 15:58
Thanks for the report; I think we'd need a few more details on how to recreate this, as a straightforward test works for me:

````
$ weave reset
$ weave launch
$ docker `weave config` run -tdi alpine /bin/sh
3c463763088e6744e85bd8737047d1579fd562007a96d939b1bdf5eaf6fb025f
bryan@bbvlx1:~/.../weaveworks/weave/test$ docker `weave config` exec -ti 3c4 cat /etc/hosts
# created by Weave - BEGIN
# container hostname
10.32.0.1    3c463763088e

# static names added with --add-host

# default localhost entries
127.0.0.1       localhost
::1             ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# created by Weave - END
````

**Comment by awh** [comment] 2016-05-24 10:42
@jbrisbin `sbt test` is compiling the test but not executing for some reason:
```
~/workspace/github.com/basho-labs/riak-test-docker [master] $ sbt test
[info] Loading project definition from /home/awh/workspace/github.com/basho-labs/riak-test-docker/project
[info] Updating {file:/home/awh/workspace/github.com/basho-labs/riak-test-docker/project/}riak-test-docker-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to riak-test-docker (in build file:/home/awh/workspace/github.com/basho-labs/riak-test-docker/)
[info] Updating {file:/home/awh/workspace/github.com/basho-labs/riak-test-docker/}riakTestDocker...
[info] Resolving com.jbrisbin.docker#akka-http-docker_2.11;0.1.0-SNAPSHOT ...
[warn] Unable to reparse com.jbrisbin.docker#akka-http-docker_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mon May 16 21:46:56 BST 2016
[warn] Choosing sonatype-snapshots for com.jbrisbin.docker#akka-http-docker_2.11;0.1.0-SNAPSHOT
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /home/awh/workspace/github.com/basho-labs/riak-test-docker/target/scala-2.11/classes...
[info] Packaging /home/awh/workspace/github.com/basho-labs/riak-test-docker/target/scala-2.11/riak-test-docker_2.11-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /home/awh/workspace/github.com/basho-labs/riak-test-docker/target/scala-2.11/test-classes...
[warn] there were two feature warnings; re-run with -feature for details
[warn] one warning found
[info] Packaging /home/awh/workspace/github.com/basho-labs/riak-test-docker/target/scala-2.11/riak-test-docker_2.11-0.1.0-SNAPSHOT-tests.jar ...
[info] Done packaging.
[info] Run completed in 18 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 7 s, completed 24-May-2016 11:39:02
```
Any clues? My environment:
```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
$ scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```

**Comment by rade** [comment] 2016-06-20 03:06
I am closing this since we cannot reproduce the problem. If steps to reproduce this become available, then please re-open.

**Closed by rade** 2016-06-20 03:06 UTC
Labels: bug, [component/proxy]
