### ISSUE TITLE
`weave stop` explodes on docker <1.9

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1816] opened 2015-12-22 12:09 UTC
I am running docker 1.8.3...
```
$ weave launch
$ weave stop
FATA: 2015/12/22 12:04:20.337536 unable to connect to docker: API error (400): client is newer than server (client API version: 1.21, server API version: 1.20)
```

**Comment by bboreham** [comment] 2015-12-22 12:13
Duplicate of #1815

**Closed by bboreham** 2015-12-22 12:13 UTC
Labels: bug, resolution/duplicate
