### ISSUE TITLE
docker run -p switch configures docker_gwbridge in iptables, not my custom weave network

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2494] opened 2016-08-31 11:22 UTC
After launching a new puppet master container like so:

```
docker run -d \
     --net ymdweave --ip 10.0.1.146 \
     --dns=172.17.0.1 --dns-search=weave.local. \
     --dns-search=zone1.weave.local --dns-search=yourmessagedelivered.com \
     --name=puppet.yourmessagedelivered.com \
     -h puppet.yourmessagedelivered.com \
     --memory=4gb \
     --restart=always --privileged=true \
     -p 8140:8140/tcp \
     -v /data/etc/apache2/puppet.yourmessagedelivered.com:/etc/apache2 \
     -v /data/var/log/apache2/puppet.yourmessagedelivered.com:/var/log/apache2 \
     -v /data/etc/puppet/puppet.yourmessagedelivered.com:/etc/puppet \
     -v /data/var/log/puppet/puppet.yourmessagedelivered.com:/var/log/puppet \
     pmng:0.2.0
```

I wind up with the following firewall rules on this container's docker host, using the containers address on the docker_gwbridge, rather than the one assigned from the ymdweave network segment:

```
root@dessalines011:~/docker-helper-scripts/lib/sh# iptables-save | grep 8140 
-A POSTROUTING -s 172.18.0.2/32 -d 172.18.0.2/32 -p tcp -m tcp --dport 8140 -j MASQUERADE
-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 8140 -j DNAT --to-destination 172.18.0.2:8140
-A DOCKER -d 172.18.0.2/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 8140 -j ACCEPT
```

and attempts then to provision another container using this puppet master result in this:

```
root@nfs:~# puppet agent --test 
Error: Could not request certificate: Failed to open TCP connection to puppet.yourmessagedelivered.com:8140 (Connection refused - connect(2) for "puppet.yourmessagedelivered.com" port 8140)
Exiting; failed to retrieve certificate and waitforcert is disabled
```

DNS is finding this:

```
root@nfs:~# host puppet.yourmessagedelivered.com
puppet.yourmessagedelivered.com has address 199.101.183.162
```

ignoring the /etc/hosts entires on my docker hosts, which includes these entries:

```
10.0.1.146      puppet.yourmessagedelivered.com
10.0.1.147      puppetdb.yourmessagedelivered.com
```

and /etc/nsswitch.conf on the docker hosts includes this line:

```
hosts:          files dns
```

What am I still missing here?  

-- Hugh

**Comment by brb** [comment] 2016-09-02 17:10
Thanks for the report.

The issue is that the `nfs` container is not able to resolve the right IP addr as it can be see from `puppet.yourmessagedelivered.com has address 199.101.183.162`.

> ignoring the /etc/hosts entires on my docker hosts, which includes these entries:

It happens because the entries are located in /etc/hosts of **the host**, but not of the container. I believe that embedded Docker DNS server does not take into consideration /etc/hosts.

> What am I still missing here?

It might be a case that you didn't specify [a custom domain name](https://www.weave.works/docs/net/latest/weavedns/managing-domains-weavedns/#local-domain) (`yourmessagedelivered.com`, in your case) when launching Weave Net. Could you provide `weave status` output?

**Comment by brb** [comment] 2016-09-02 17:11
One more thing: are you able to `ping 10.0.1.146` from the `nfs` container?

**Comment by hesco** [comment] 2016-09-03 22:36
Martynas:

Thank you so much.  This looks much better:

```
root@nfs:~# host puppet.yourmessagedelivered.com 
puppet.yourmessagedelivered.com has address 10.0.1.146
```
While I had previously been able to ping an IP across docker hosts, to get this useful result required that I relaunch my network on each host like so:
```
/usr/local/bin/weave launch --ipalloc-range 10.0.0.0/20 \
     --dns-domain yourmessagedelivered.com \
     --ipalloc-default-subnet 10.0.2.0/24 \
     $LIST_OF_PEERS
```
and then stopped and started the nfs container on one host and the puppet container on the other host, 
and now I can successfully resolve a host name in my weave hosted DNS database.  Moving on now to the next issue.  

you are a life saver.

**Comment by hesco** [comment] 2016-09-03 22:40
So, that moves me a significant step closer to the goal, but leaves unaddressed the fact that the iptables rules seem to ignore the weave network, but instead configure things on the docker_gwbridge  network.  Is this happening in weave?  Or in docker?  And what can I do about it so that my weave network packets get properly MASQUERADED and routed to the appropriate container?

```
root@dessalines011:~/docker-helper-scripts/lib/sh# iptables-save | grep 8140
-A POSTROUTING -s 172.18.0.2/32 -d 172.18.0.2/32 -p tcp -m tcp --dport 8140 -j MASQUERADE
-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 8140 -j DNAT --to-destination 172.18.0.2:8140
-A DOCKER -d 172.18.0.2/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 8140 -j ACCEPT
```

**Comment by brb** [comment] 2016-09-05 07:11
The listed iptable rules are installed by Docker and they get installed because of the `-p 8140:8140/tcp` param passed to `docker run`.

If you intend to access the puppet master container only from containers connected to the same weave network, you do not need to publish any port, because such containers can connect directly to the puppet master container, i.e. by using `puppet.yourmessagedelivered.com:8140` as a destination addr.

**Comment by hesco** [comment] 2016-09-05 20:43
I do want this puppet master to serve nodes outside of my local weave SDN.  So I do need to expose, or export that port, I just need to make sure doing so does not preclude my ability to access that service from inside the SDN.  That does not seem to be an issue, though.  Still sorting this out.  Thanks for your help with this.

**Comment by brb** [comment] 2016-09-06 06:56
Publishing a port with Docker (`-p`) should work together with Weave. Just don't forget to install necessary routes if you are going to access the puppet master from other hosts.

Alternatively, you could expose the Weave network with `weave expose` and make the service accessible as it is documented [here](https://www.weave.works/docs/net/latest/using-weave/service-management/#exporting).

**Comment by brb** [comment] 2016-09-13 14:07
I'm closing this issue as all the questions were answered.

**Closed by brb** 2016-09-13 14:07 UTC
Labels: question
