### ISSUE TITLE
Weave returns an error when trying to pull the latest from DockerHub

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1666] opened 2015-11-10 19:31 UTC
Run this Vagrant file to provision 2 VMs on VirtualBox:

https://github.com/weaveworks/guides/blob/ubuntu-all-edits/ubuntu-all-in-one/Vagrantfile

Next, try running the shell script to launch weave here: 

https://github.com/weaveworks/guides/blob/ubuntu-all-edits/ubuntu-all-in-one/launch-simple-demo.sh

(this will fail and weave won't launch)

then ssh onto one of the VMs and launch weave from there: 

```bash
weave launch
Unable to find image 'weaveworks/weave:1.2.1' locally
1.2.1: Pulling from weaveworks/weave
Pulling repository docker.io/weaveworks/weave
Status: Downloaded newer image for weaveworks/weave:1.2.1
docker.io/weaveworks/weave: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
Error deleting container: Error response from daemon: Unable to remove filesystem for f101788e50646c12e09b3f758301f57d884c9e4649536e4f8a4798a56576821d: remove /var/lib/docker/containers/f101788e50646c12e09b3f758301f57d884c9e4649536e4f8a4798a56576821d/mqueue: device or resource busy
```

Weave does, however launch afterward despite the message. 

machine configuration is as follows: 

```bash
docker info
Containers: 5
Images: 75
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: weave-gs-01
ID: EBJ4:DO6U:647D:S7IJ:55ZL:2CGO:JC54:K6BU:NJNB:AEEO:Q2YF:M7NJ
WARNING: No swap limit support
```

**Comment by bboreham** [comment] 2015-11-11 11:19
I have replicated the symptom, thanks.

The error comes when Docker tries to remove the container that is running the main weave script.

It does not come if you do something simpler like `weave version`.

I shall continue to investigate.

**Comment by bboreham** [comment] 2015-11-11 13:20
Filed https://github.com/docker/docker/issues/17902

Confirmed this does not happen if you use a newer kernel.  I guess we should update that `Vagrantfile`.

**Comment by bboreham** [comment] 2015-11-11 16:25
Looks like a duplicate of #1647

**Closed by bboreham** 2015-11-11 16:25 UTC
