### ISSUE TITLE
After upgraded to latest weaveexec weave images, the issue is still there: weave Net 2.4.1 on macosx 10.13.6

### ISSUE THREAD

**Issue by guijun** [weaveworks/weave#3425] opened 2018-10-05 02:37 UTC
No DNS entry added after container started.
steps to repoduce:

Docker Version 18.06.1-ce-mac73 (26764)
install weave 2.4.1 by curl

update /usr/local/bin/weave with:
#SCRIPT_VERSION="2.4.1"
SCRIPT_VERSION="latest"

eval $(weave env)

docker run --name AAA bash /usr/bash

weave ps

No entry listed for new container.

**Comment by brb** [comment] 2018-10-08 14:11
It is a duplicate of https://github.com/weaveworks/weave/issues/3405 which fix hasn't been released yet.

**Closed by brb** 2018-10-08 14:11 UTC
