### ISSUE TITLE
Weave removing the VM access 

### ISSUE THREAD

**Issue by cooligc** [weaveworks/weave#2835] opened 2017-03-09 14:21 UTC
Hi All,

I have followed [kubeadm](https://kubernetes.io/docs/getting-started-guides/kubeadm/) installation.

In Step3 : I have installed weave network ` kubectl apply -f https://git.io/weave-kube` .

When ever I am installing weave network , I am not able to access the VM and network to the VM is getting terminated.

Point to note : 

1. I am working behind corporate proxy
2. Output of uname -a
      `Linux minion2 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux`
3. Removed the proxy details in this post as I cannot expose it.
4. docker info output
```
[root@minion2 ~]# docker info
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 14
Server Version: 1.12.4
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.781 GiB
Name: minion2
ID: Q6KC:VGM5:DE7P:I2TW:H2SQ:A3CI:GFRM:IPLZ:MKA5:SHJI:6CLP:4XSU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Comment by bboreham** [comment] 2017-03-09 14:25
@cooligc is your VM's own network address inside the range of IP addresses used by Weave by default?  (10.32.0.0/12)

To check, run `ip route` and `ip addr` on the host.

**Comment by cooligc** [comment] 2017-03-09 14:30
No , It is not. The range starts with 15.XX.XX.XX

**Comment by bboreham** [comment] 2017-03-09 14:46
@cooligc could you say what exactly you mean by "network to the VM is getting terminated"?  Who or what terminated it?  Is there an error message?

Is it possible to supply the output of `iptables-save` from before you run the `kubectl apply`?

What Weave Net does on the host:
 1. creates a bridge named `weave`
 2. gives the bridge an IP address in Weave Net's range, which in turn sets up a route for that subnet
 3. adds masquerading (nat) rules for anything leaving the bridge
 4. adds iptables rules to only allow permitted traffic onto the bridge

Right now I can't think of anything other than a subnet overlap that would break your host network.

**Comment by cooligc** [comment] 2017-03-09 15:04
@bboreham 
1. The VM is in ESXi . and The same VM is accessible from localhost. 
2. After installing the weave network , the putty session from localhost to VM is getting terminated . 
3. VM communicates when we are checking in vSphere console(in same subnet) using ssh.

**Comment by bboreham** [comment] 2017-03-09 15:21
This report looks very like #2289, which was a kernel bug fixed in 3.13.  Can you check into that please?

**Comment by cooligc** [comment] 2017-03-14 11:46
Tried with kernel v4.10 with RHEL 7.3 . No Change in the behavior.

```
[root@gru ~]# uname -a
Linux gru 4.10.2-1.el7.elrepo.x86_64 #1 SMP Sun Mar 12 13:25:09 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by bboreham** [comment] 2017-03-14 13:02
OK, thanks.  

Can you expand on this a bit?
> VM communicates when we are checking in vSphere console(in same subnet) using ssh.

Do you mean you lost one link to the VM but you have another that works?  What is the difference between those two links?

**Comment by cooligc** [comment] 2017-03-14 13:24
Hey @bboreham ,

Here are the 2 scenarios,

1. Lets say, I have started master , installed weave network then started the minion
       minion is able to join to the network. (We could see the network interface in both the system)
       Then, after some second , VMs are out of reach
2. Lets say, Master is started and weave is installed, then after some second , we loose the control in master.
    Point to remember here, We have not join the minion on to master.

**Both the VMs are accessible from vSphere console although it is not accessible using putty ssh**

**Comment by bboreham** [comment] 2017-03-14 13:43
Ok, if you can access the machine through the vSphere console, could you post the output before and after the failure of these commands:

    ip addr
    ip route
    sudo iptables-save

Thanks

**Comment by cooligc** [comment] 2017-03-17 12:14
Hey @bboreham ,

Please find the required details. Sorry for the delay.
[After.txt](https://github.com/weaveworks/weave/files/850474/After.txt)
[Before.txt](https://github.com/weaveworks/weave/files/850476/Before.txt)

**Comment by bboreham** [comment] 2017-03-17 13:18
That looks like before installation of Kubernetes and after installation of everything.  Previously you had said it breaks at step 3, which ought to be a smaller set of changes.

This line puzzles me:

    -A KUBE-SEP-TMSHWDTNCTVPIVXI -s <INTERNAL_IP>/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ

I can't see why Kubernetes would want to NAT an IP on your network.  Is that IP the one that you connect via ssh over?

Beyond that I cannot spot any reason why it would fail.

**Comment by bboreham** [comment] 2017-03-17 13:51
@cooligc I tried to create an RHEL machine to see if it would break the same way for me, but I failed at the step `yum install docker` - there is no such package.  How did you install it?

**Comment by bboreham** [comment] 2017-03-17 14:26
https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo 404's

**Comment by cooligc** [comment] 2017-03-17 14:48
Unfortunately , the url got change . We have followed the below url, please refer.
https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository

**Comment by marccarre** [comment] 2017-03-21 16:17
@cooligc this documentation currently doesn't mention `docker-engine` as a valid package:

> Older versions of Docker were called docker or docker-engine. If these are installed, uninstall them, along with associated dependencies.

though it seems it is what you are using according to your [previous comment](https://github.com/weaveworks/weave/issues/2835#issuecomment-287367607).

1) Are you using:

- `docker-engine`?
- `docker-ce`?
- `docker-ee`?

2) Which specific version are you using?

**Comment by cooligc** [comment] 2017-03-22 12:57
@marccarre 

I am using docker-engine.
docker : Server Version: 1.12.4

**Comment by marccarre** [comment] 2017-03-23 17:37
Hi @cooligc, I tried to reproduce your issue on a small cluster of machines as similar as possible to yours -- details to follow.
After a few minutes (not seconds), on one of the nodes, I did observe that the SSH session got terminated with the below error client side:

```
# packet_write_wait: Connection to 104.154.185.203 port 22: Broken pipe
```

Is that what you observed as well and meant by the following?

> I am not able to access the VM and network to the VM is getting terminated.

> then after some second , we loose the control in master.

**Comment by marccarre** [comment] 2017-03-23 17:39
Details on the setup:
```
# uname -a
Linux marc-0 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /etc/*release*
CentOS Linux release 7.3.1611 (Core) 
Derived from Red Hat Enterprise Linux 7.3 (Source)
cat: /etc/lsb-release.d: Is a directory
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 
cpe:/o:centos:centos:7
```

```
# docker version
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Mon Dec 12 23:41:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Mon Dec 12 23:41:49 2016
 OS/Arch:      linux/amd64
```

Note that I had to drop `docker` from the list of packages listed in the `kubeadm` instructions as it would conflict with `docker-engine`:
```
Error: docker-engine conflicts with 2:docker-1.12.6-11.el7.centos.x86_64
Error: docker-engine-selinux conflicts with 2:container-selinux-2.9-4.el7.noarch
```

```
# kubectl --kubeconfig /etc/kubernetes/kubelet.conf version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ diff before.txt after.txt
1c1
< Before:
---
> After:
13c13
<        valid_lft 84230sec preferred_lft 84230sec
---
>        valid_lft 83756sec preferred_lft 83756sec
17a18,33
> 4: datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1376 qdisc noqueue state UNKNOWN qlen 1000
>     link/ether b6:09:08:9f:cc:23 brd ff:ff:ff:ff:ff:ff
> 6: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1376 qdisc noqueue state UP qlen 1000
>     link/ether be:c8:e2:3e:f6:f8 brd ff:ff:ff:ff:ff:ff
>     inet 10.32.0.1/12 scope global weave
>        valid_lft forever preferred_lft forever
> 7: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
>     link/ether 6a:42:b7:65:6f:0f brd ff:ff:ff:ff:ff:ff
> 9: vethwe-datapath@vethwe-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1376 qdisc noqueue master datapath state UP qlen 1000
>     link/ether 9a:25:15:69:13:f2 brd ff:ff:ff:ff:ff:ff
> 10: vethwe-bridge@vethwe-datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1376 qdisc noqueue master weave state UP qlen 1000
>     link/ether 2e:20:58:65:f5:f1 brd ff:ff:ff:ff:ff:ff
> 13: vethwepla306bbf@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1376 qdisc noqueue master weave state UP 
>     link/ether 1e:a8:6a:ad:68:6e brd ff:ff:ff:ff:ff:ff link-netnsid 0
> 14: vxlan-6784: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65470 qdisc noqueue master datapath state UNKNOWN qlen 1000
>     link/ether 72:c9:fe:f3:3e:cc brd ff:ff:ff:ff:ff:ff
20a37
> 10.32.0.0/12 dev weave  proto kernel  scope link  src 10.32.0.1 
27d43
< 
31,32c47,48
< :OUTPUT ACCEPT [19:1206]
< :POSTROUTING ACCEPT [19:1206]
---
> :OUTPUT ACCEPT [0:0]
> :POSTROUTING ACCEPT [0:0]
38a55,56
> :KUBE-SEP-SZZ7MOWKTWUFXIJT - [0:0]
> :KUBE-SEP-UJJNLSZU6HL4F5UO - [0:0]
57a76
> :WEAVE - [0:0]
70a90
> -A POSTROUTING -j WEAVE
76a97,101
> -A KUBE-SEP-SZZ7MOWKTWUFXIJT -s 10.32.0.2/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
> -A KUBE-SEP-SZZ7MOWKTWUFXIJT -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.32.0.2:53
> -A KUBE-SEP-UJJNLSZU6HL4F5UO -s 10.32.0.2/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
> -A KUBE-SEP-UJJNLSZU6HL4F5UO -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.32.0.2:53
> -A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
79d103
< -A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
80a105
> -A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-UJJNLSZU6HL4F5UO
82a108
> -A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-SZZ7MOWKTWUFXIJT
92a119,121
> -A WEAVE -s 10.32.0.0/12 -d 224.0.0.0/4 -j RETURN
> -A WEAVE ! -s 10.32.0.0/12 -d 10.32.0.0/12 -j MASQUERADE
> -A WEAVE -s 10.32.0.0/12 ! -d 10.32.0.0/12 -j MASQUERADE
96,100c125,129
< :PREROUTING ACCEPT [25281:213320680]
< :INPUT ACCEPT [25279:213319804]
< :FORWARD ACCEPT [0:0]
< :OUTPUT ACCEPT [24429:1613856]
< :POSTROUTING ACCEPT [24447:1617496]
---
> :PREROUTING ACCEPT [35288:299468970]
> :INPUT ACCEPT [34487:299226803]
> :FORWARD ACCEPT [763:236429]
> :OUTPUT ACCEPT [32301:2606954]
> :POSTROUTING ACCEPT [33128:2853628]
127,129c156,158
< :INPUT ACCEPT [25279:213319804]
< :FORWARD ACCEPT [0:0]
< :OUTPUT ACCEPT [24429:1613856]
---
> :INPUT ACCEPT [34487:299226803]
> :FORWARD ACCEPT [763:236429]
> :OUTPUT ACCEPT [32301:2606954]
139,140c168,169
< :PREROUTING ACCEPT [25281:213320680]
< :OUTPUT ACCEPT [24429:1613856]
---
> :PREROUTING ACCEPT [35288:299468970]
> :OUTPUT ACCEPT [32301:2606954]
150c179
< :OUTPUT ACCEPT [413:41307]
---
> :OUTPUT ACCEPT [82:15418]
175a205,207
> :WEAVE-NPC - [0:0]
> :WEAVE-NPC-DEFAULT - [0:0]
> :WEAVE-NPC-INGRESS - [0:0]
183a216,221
> -A INPUT -d 172.17.0.1/32 -i docker0 -p tcp -m tcp --dport 6783 -j DROP
> -A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6783 -j DROP
> -A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6784 -j DROP
> -A INPUT -i docker0 -p udp -m udp --dport 53 -j ACCEPT
> -A INPUT -i docker0 -p tcp -m tcp --dport 53 -j ACCEPT
> -A FORWARD -i docker0 -o weave -j DROP
197a236,240
> -A FORWARD -o weave -j WEAVE-NPC
> -A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
> -A FORWARD -o weave -j DROP
> -A FORWARD -i weave ! -o weave -j ACCEPT
> -A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
221,222c264,269
< -A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
< -A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreachable
---
> -A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
> -A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
> -A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
> -A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
> -A WEAVE-NPC-DEFAULT -m set --match-set weave-k?Z;25^M}|1s7P3|H9i;*;MhG dst -j ACCEPT
> -A WEAVE-NPC-DEFAULT -m set --match-set weave-iuZcey(5DeXbzgRFs8Szo]<@p dst -j ACCEPT
```
[after.txt](https://github.com/weaveworks/weave/files/865618/after.txt)
[before.txt](https://github.com/weaveworks/weave/files/865620/before.txt)

**Comment by marccarre** [comment] 2017-03-24 13:57
Actually, when trying the same steps again today on fresh VMs (I wanted to debug things further), I cannot seem to reproduce what I had yesterday anymore, so it could just have been my SSH connection timing out.

@cooligc, 
1. as mentioned previously, it would be good to know the **exact** error message you get, if you get any;
2. does this happen consistently?
3. does this still happen with latest Docker, Kubernetes and Weave Net versions? (e.g. Kubernetes only keeps the latest version in their repository, and a new version has been released since you opened this issue so I'm probably not using the same version as you were)
4. if you want us to try to reproduce your issue, we would need the **exact commands** you ran, and not an approximation of some instructions on a website which has changed since you visited it, like we are doing here. Indeed, we may be missing some important detail in the process here. 

Please either keep us posted.

**Comment by marccarre** [comment] 2017-03-31 13:52
@cooligc, I'll close the issue for now as we unfortunately cannot reproduce your issue.
Feel free to reopen with answers to the above questions & more specific steps to help us reproduce it.

**Closed by marccarre** 2017-03-31 13:52 UTC
Labels: state/investigating

**Comment by ajitchahal** [comment] 2019-05-29 20:26
Same issue with me 
 I am just trying deploying k8s to vanilla aws ec2s, I am using kubeadm, once i run `kubectl apply -f "https://cloud.weave.works/k8s/net?IPALLOC_RANGE=172.30.0.0/16&k8s-version=$(kubectl version | base64 | tr -d '\n')"` as per the docs `https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-changing-configuration-options` my ssh connection to master ec2 instance drops and i can not SSH to the VM anymore, is because weave net’s default CIDR range 10.32.0.0/12 conflicts with AWS?

How can i specify another CIDR?

**Comment by ajitchahal** [comment] 2019-05-29 20:27
for info: my aws bastian/jumpbox has an ip of the range 10-37-12-17...

**Comment by ajitchahal** [comment] 2019-05-29 20:35
I am just trying deploying k8s to vanilla aws ec2s, I am using kubeadm, once i run `kubectl apply -f "https://cloud.weave.works/k8s/net?IPALLOC_RANGE=172.30.0.0/16&k8s-version=$(kubectl version | base64 | tr -d '\n')"` as per the docs `https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-changing-configuration-options` my ssh connection to master ec2 instance drops and i can not SSH to the VM any more, is because weave net’s default CIDR range 10.32.0.0/12 conflicts with AWS?

**Comment by dboc** [comment] 2020-02-10 17:20
This is a old! 
But it happens to me too, but it is not a issue. 
Weave use the network 10.32.0.0/12 as default and my workstation is on that range. So you must use another range. See docs: https://www.weave.works/docs/net/latest/tasks/ipam/configuring-weave/

**Comment by bboreham** [comment] 2020-02-10 17:48
When using Kubernetes you probably want to set `IPALLOC_RANGE` as described at https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#configuration-options
